{
  "hash": "f36be5a3f96dc46ea82db0993788faeb",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"ACP sur les données Real Estate\"\nauthor: \"Guillaume Guex\"\nlang: fr\n---\n\n## Présentation\n\nDans ce notebook (<https://bookdown.org/yihui/rmarkdown/>), nous allons donner un \nexemple d'**ACP** sur les données `realestate_data.xlsx` (<https://archive.ics.uci.edu/dataset/477/real+estate+valuation+data+set>), qui \ncontiennent des informations sur les prix de l'immobilier à Taïwan. Ce jeu de\ndonnées est généralement utilisé pour prédire le prix de l'immobilier en \nfonction de différentes variables explicatives (âge du bâtiment, distance aux transports, \npositon, etc).\n\n## Chargement des données et pré-traitements\n\nOn commence par charger les données et jeter un coup d'œil à leur \nstructure.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Charger les bibliothèques nécessaires\nlibrary(tidyverse)\n```\n\n::: {.cell-output .cell-output-stderr}\n\n```\n── Attaching core tidyverse packages ──────────────────────── tidyverse 2.0.0 ──\n✔ dplyr     1.2.1     ✔ readr     2.2.0\n✔ forcats   1.0.1     ✔ stringr   1.6.0\n✔ ggplot2   4.0.3     ✔ tibble    3.3.1\n✔ lubridate 1.9.5     ✔ tidyr     1.3.2\n✔ purrr     1.2.2     \n── Conflicts ────────────────────────────────────────── tidyverse_conflicts() ──\n✖ dplyr::filter() masks stats::filter()\n✖ dplyr::lag()    masks stats::lag()\nℹ Use the conflicted package (<http://conflicted.r-lib.org/>) to force all conflicts to become errors\n```\n\n\n:::\n\n```{.r .cell-code}\nlibrary(readxl)\nlibrary(FactoMineR)\nlibrary(factoextra)\n```\n\n::: {.cell-output .cell-output-stderr}\n\n```\nWelcome to factoextra!\nWant to learn more? See two factoextra-related books at https://www.datanovia.com/en/product/practical-guide-to-principal-component-methods-in-r/\n```\n\n\n:::\n\n```{.r .cell-code}\nlibrary(knitr)\nlibrary(psych)\n```\n\n::: {.cell-output .cell-output-stderr}\n\n```\n\nAttachement du package : 'psych'\n\nLes objets suivants sont masqués depuis 'package:ggplot2':\n\n    %+%, alpha\n```\n\n\n:::\n\n```{.r .cell-code}\n# Charger les données\nreal_estate = read_excel(\"realestate_data.xlsx\")\n\n# Afficher les premières lignes des données\nkable(head(real_estate))\n```\n\n::: {.cell-output-display}\n\n\n| No| transaction_date| house_age| distance_to_station| n_stores| latitude| longitude| house_price_unit|\n|--:|----------------:|---------:|-------------------:|--------:|--------:|---------:|----------------:|\n|  1|         2012.917|      32.0|            84.87882|       10| 24.98298|  121.5402|             37.9|\n|  2|         2012.917|      19.5|           306.59470|        9| 24.98034|  121.5395|             42.2|\n|  3|         2013.583|      13.3|           561.98450|        5| 24.98746|  121.5439|             47.3|\n|  4|         2013.500|      13.3|           561.98450|        5| 24.98746|  121.5439|             54.8|\n|  5|         2012.833|       5.0|           390.56840|        5| 24.97937|  121.5425|             43.1|\n|  6|         2012.667|       7.1|          2175.03000|        3| 24.96305|  121.5125|             32.1|\n\n\n:::\n:::\n\n\nOn regarde combien de lignes possède le jeu de données.\n\n::: {.cell}\n\n```{.r .cell-code}\nnrow(real_estate)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 414\n```\n\n\n:::\n:::\n\nIl y a 414 observations.\n\nLa variable \"transaction_date\" contient une date, qui n'a pas été lue \ncorrectement. On ne va garder que l'année qui se situe avant le point\n\n::: {.cell}\n\n```{.r .cell-code}\nreal_estate = real_estate %>%\n  mutate(transaction_date = as.numeric(substr(transaction_date, 1, 4)))\n```\n:::\n\n\nOn va également enlèver la numéro de maison\n\n::: {.cell}\n\n```{.r .cell-code}\nreal_estate = real_estate %>%\n  select(-No)\nglimpse(real_estate)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nRows: 414\nColumns: 7\n$ transaction_date    <dbl> 2012, 2012, 2013, 2013, 2012, 2012, 2012, 2013, 20…\n$ house_age           <dbl> 32.0, 19.5, 13.3, 13.3, 5.0, 7.1, 34.5, 20.3, 31.7…\n$ distance_to_station <dbl> 84.87882, 306.59470, 561.98450, 561.98450, 390.568…\n$ n_stores            <dbl> 10, 9, 5, 5, 5, 3, 7, 6, 1, 3, 1, 9, 5, 4, 4, 2, 6…\n$ latitude            <dbl> 24.98298, 24.98034, 24.98746, 24.98746, 24.97937, …\n$ longitude           <dbl> 121.5402, 121.5395, 121.5439, 121.5439, 121.5425, …\n$ house_price_unit    <dbl> 37.9, 42.2, 47.3, 54.8, 43.1, 32.1, 40.3, 46.7, 18…\n```\n\n\n:::\n:::\n\nToutes les autres variables sont numériques, on peut donc effectuer une ACP.\n\n-----------------\n\n## ACP\n\nOn effectue une ACP sur les données en utilisant la fonction `PCA` du\npackage `FactoMineR`.\n\n::: {.cell}\n\n```{.r .cell-code}\n# Effectuer l'ACP\npca_res = PCA(real_estate, graph = FALSE)\n```\n:::\n\n\nL'ACP est effectuée, on peut maintenant observer les différents résultats\n\n### Variance expliquée\n\nCommençons par observer la **valeurs propres** qui expriment la variance expliquée\nsur chaque facteur.\n\n::: {.cell}\n\n```{.r .cell-code}\neig_vals = get_eigenvalue(pca_res)\nkable(eig_vals)\n```\n\n::: {.cell-output-display}\n\n\n|      | eigenvalue| variance.percent| cumulative.variance.percent|\n|:-----|----------:|----------------:|---------------------------:|\n|Dim.1 |  3.2715008|        46.735726|                    46.73573|\n|Dim.2 |  1.0771175|        15.387393|                    62.12312|\n|Dim.3 |  0.9983295|        14.261850|                    76.38497|\n|Dim.4 |  0.6361083|         9.087262|                    85.47223|\n|Dim.5 |  0.5533467|         7.904953|                    93.37718|\n|Dim.6 |  0.3185875|         4.551251|                    97.92843|\n|Dim.7 |  0.1450097|         2.071567|                   100.00000|\n\n\n:::\n:::\n\n\nOn peut visualiser cette variance expliquée par chaque facteur avec \nle **screegraph**\n\n::: {.cell}\n\n```{.r .cell-code}\nfviz_screeplot(pca_res, addlabels = TRUE, ylim = c(0, 50))\n```\n\n::: {.cell-output-display}\n![](acp_realestate_files/figure-html/unnamed-chunk-7-1.png){width=672}\n:::\n:::\n\n\nGrâce à ces deux éléments, on pourrait décider du nombre de facteurs selon \ndifférents critère : \n\n  * Selon le *crière de Joliffe* (garder 90% de la variance), on garderait\n  5 facteurs.\n  * Selon le *critère de Kaiser* (valeurs propres > moyenne = 1), on garderait\n  2 facteurs.\n  * Selon le *critère de Cattell ou du coude* (chercher un coude dans le screegraph), on\n  garderait 1 facteur.\n\nEffectuons un **test de Bartlett** pour vérifier que l'ACP est pertinente\n\n::: {.cell}\n\n```{.r .cell-code}\ncortest.bartlett(real_estate)\n```\n\n::: {.cell-output .cell-output-stderr}\n\n```\nR was not square, finding R from data\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stdout}\n\n```\n$chisq\n[1] 1172.576\n\n$p.value\n[1] 4.247946e-235\n\n$df\n[1] 21\n```\n\n\n:::\n:::\n\n\nL'hypothèse H0 : \"toutes les valeurs propres sont égales\" est largement rejetée, \nnotre ACP est donc pertinente.\n\n### Cercle des corrélations\n\nOn peut visualiser le **cercle des corrélations** pour observer les\ncontributions des variables aux différents facteurs.\n\n::: {.cell}\n\n```{.r .cell-code}\nfviz_pca_var(pca_res, col.var = \"contrib\",\n             gradient.cols = c(\"#00AFBB\", \"#E7B800\", \"#FC4E07\"),\n             repel = TRUE)\n```\n\n::: {.cell-output-display}\n![](acp_realestate_files/figure-html/unnamed-chunk-9-1.png){width=672}\n:::\n:::\n\n\nLes *communalités* (vues plus loin) des variables sur les deux premiers facteurs ont \nété utilisées pour la coloration. Ce graphique exprime **46.7% + 15.4% = 62.1% \nde la variance totale**.\n\nCe graphique montre que le **premier facteur** comprends les variables :\n\n* (positivement) le prix au m2\n* (positivement) la latitude \n* (positivement) la longitude \n* (positivement) le nombre de commerces\n* (négativement) la distance aux transports publics\n\nOn pourrait nommer cette axe **\"Attractivité du bâtiment\"**.\n\nLe **deuxième facteur** lie :\n\n* (positivement) âge de la maison\n* (positivement) date de vente \n\nEn réalité cet axe est presque entièrement lié à l'âge de la maison, qui semble\northogonale à toutes les autres variables.\n\nCe graphique est basé sur les **saturations** (correlations entre variables et facteurs)\n\n::: {.cell}\n\n```{.r .cell-code}\nsaturations = pca_res$var$coord[, 1:2]\nkable(saturations)\n```\n\n::: {.cell-output-display}\n\n\n|                    |      Dim.1|      Dim.2|\n|:-------------------|----------:|----------:|\n|transaction_date    |  0.0269404|  0.4082392|\n|house_age           | -0.0697893|  0.9183115|\n|distance_to_station | -0.9190342| -0.0096036|\n|n_stores            |  0.7510695|  0.1229386|\n|latitude            |  0.7290189|  0.1515971|\n|longitude           |  0.7997217| -0.0237128|\n|house_price_unit    |  0.8283428| -0.1685592|\n\n\n:::\n:::\n\n\nLes **saturations carrées** exprime le pourcentage de variance d'une variable\nexpliquée par un facteur.\n\n::: {.cell}\n\n```{.r .cell-code}\nkable(saturations^2)\n```\n\n::: {.cell-output-display}\n\n\n|                    |     Dim.1|     Dim.2|\n|:-------------------|---------:|---------:|\n|transaction_date    | 0.0007258| 0.1666592|\n|house_age           | 0.0048706| 0.8432959|\n|distance_to_station | 0.8446239| 0.0000922|\n|n_stores            | 0.5641055| 0.0151139|\n|latitude            | 0.5314686| 0.0229817|\n|longitude           | 0.6395548| 0.0005623|\n|house_price_unit    | 0.6861518| 0.0284122|\n\n\n:::\n:::\n\n\nEt les **communalités** sont la somme de ces dernières sur les deux premiers facteurs.\n\n::: {.cell}\n\n```{.r .cell-code}\nkable(rowSums(saturations^2))\n```\n\n::: {.cell-output-display}\n\n\n|                    |         x|\n|:-------------------|---------:|\n|transaction_date    | 0.1673850|\n|house_age           | 0.8481665|\n|distance_to_station | 0.8447161|\n|n_stores            | 0.5792194|\n|latitude            | 0.5544503|\n|longitude           | 0.6401171|\n|house_price_unit    | 0.7145640|\n\n\n:::\n:::\n\n\nOn voit que les variables \"house_age\" (84.81%), \"distance_to_station\" (84.47%) et \n\"house_price_unit\" (71.45%) sont les mieux exprimées sur ces axes.\n\n### Coordonnées factorielles\n\nOn peut observer les **coordonnées factorielles** des observations sur les deux premiers\nfacteurs.\n\n::: {.cell}\n\n```{.r .cell-code}\nfviz_pca_ind(pca_res)\n```\n\n::: {.cell-output-display}\n![](acp_realestate_files/figure-html/unnamed-chunk-13-1.png){width=672}\n:::\n:::\n\n\nLes individus étant anonymes dans ce jeu de données, ce graphique n'est pas très\ninformatif. On pourrait les colorer selon une variable catégorielle, mais il n'y\nen a pas dans ce jeu de données. \n\nNous allons ici les colorer selon un gradient d'une des variables numériques. \nCommençons par \"house_age\".\n\n::: {.cell}\n\n```{.r .cell-code}\nfviz_pca_ind(pca_res,\n             geom=\"point\",\n             col.ind = real_estate$house_age,\n             gradient.cols = c(\"#00AFBB\", \"#E7B800\", \"#FC4E07\"))\n```\n\n::: {.cell-output-display}\n![](acp_realestate_files/figure-html/unnamed-chunk-14-1.png){width=672}\n:::\n:::\n\n\nComme attendu, les maisons plus récentes (en bleu) se situent en bas du graphique\n(âge faible sur le deuxième facteur).\n\nFaisons de même avec \"distance_to_station\".\n\n::: {.cell}\n\n```{.r .cell-code}\nfviz_pca_ind(pca_res,\n             geom=\"point\",\n             col.ind = real_estate$distance_to_station,\n             gradient.cols = c(\"#00AFBB\", \"#E7B800\", \"#FC4E07\"))\n```\n\n::: {.cell-output-display}\n![](acp_realestate_files/figure-html/unnamed-chunk-15-1.png){width=672}\n:::\n:::\n\n\nOn observe que les maisons plus proches des transports publics (en bleu) se situent\nà droite du graphique (corrélation négative avec le premier facteur).\n\nFinalement idem avec \"house_price_unit\".\n\n::: {.cell}\n\n```{.r .cell-code}\nfviz_pca_ind(pca_res,\n             geom=\"point\",\n             col.ind = real_estate$house_price_unit,\n             gradient.cols = c(\"#00AFBB\", \"#E7B800\", \"#FC4E07\"))\n```\n\n::: {.cell-output-display}\n![](acp_realestate_files/figure-html/unnamed-chunk-16-1.png){width=672}\n:::\n:::\n\n\nOn observe que les logements les plus chers (en rouge) se situent vers la droite.\n\n-----------------\n\n\n\n",
    "supporting": [
      "acp_realestate_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}