project:
  type: website
  output-dir: _site
  preview:
    port: 4200        
    browser: true

website:
  title: "My Portfolio"
  navbar:
    left:
      - text: "About Me"
        href: index.qmd
      - text: "Teaching"
        href: teaching/index.qmd
      - text: "Visualizations"
        href: viz/index.qmd
      - text: "Simulations"
        href: sim/index.qmd

format:
  html:
    theme: cosmo
    toc: true