{
  "hash": "0e42afb19c3d5d96cd2be2d3cb18bcb4",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"Régression multiple sur les données SeoulBike\"\nauthor: \"Guillaume Guex\"\nlang: fr\n---\n\n## Présentation\n\nDans ce notebook (<https://bookdown.org/yihui/rmarkdown/>), nous allons donner un \nexemple de **régression multiple** sur les données `SeoulBikeData.csv` (<https://archive.ics.uci.edu/dataset/560/seoul+bike+sharing+demand>), qui \ncontiennent des informations sur le nombre de locations de vélos à Séoul en \nfonction de différentes variables explicatives (température, humidité, saison, etc).\n\n## Chargement des données et pré-traitements\n\nOn commence par charger les données et jeter un coup d'œil rapide à leur \nstructure.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Charger les bibliothèques nécessaires\nlibrary(tidyverse)\n```\n\n::: {.cell-output .cell-output-stderr}\n\n```\n── Attaching core tidyverse packages ──────────────────────── tidyverse 2.0.0 ──\n✔ dplyr     1.2.1     ✔ readr     2.2.0\n✔ forcats   1.0.1     ✔ stringr   1.6.0\n✔ ggplot2   4.0.3     ✔ tibble    3.3.1\n✔ lubridate 1.9.5     ✔ tidyr     1.3.2\n✔ purrr     1.2.2     \n── Conflicts ────────────────────────────────────────── tidyverse_conflicts() ──\n✖ dplyr::filter() masks stats::filter()\n✖ dplyr::lag()    masks stats::lag()\nℹ Use the conflicted package (<http://conflicted.r-lib.org/>) to force all conflicts to become errors\n```\n\n\n:::\n\n```{.r .cell-code}\nlibrary(knitr)\n\n# Charger les données\nseoul_bike = read.csv(\"SeoulBikeData.csv\", stringsAsFactors = TRUE)\n\n# Afficher les premières lignes des données\nkable(head(seoul_bike))\n```\n\n::: {.cell-output-display}\n\n\n|Date       | Rented.Bike.Count| Hour| Temperature.C.| Humidity...| Wind.speed..m.s.| Visibility..10m.| Dew.point.temperature.C.| Solar.Radiation..MJ.m2.| Rainfall.mm.| Snowfall..cm.|Seasons |Holiday    |Functioning.Day |\n|:----------|-----------------:|----:|--------------:|-----------:|----------------:|----------------:|------------------------:|-----------------------:|------------:|-------------:|:-------|:----------|:---------------|\n|01/12/2017 |               254|    0|           -5.2|          37|              2.2|             2000|                    -17.6|                       0|            0|             0|Winter  |No Holiday |Yes             |\n|01/12/2017 |               204|    1|           -5.5|          38|              0.8|             2000|                    -17.6|                       0|            0|             0|Winter  |No Holiday |Yes             |\n|01/12/2017 |               173|    2|           -6.0|          39|              1.0|             2000|                    -17.7|                       0|            0|             0|Winter  |No Holiday |Yes             |\n|01/12/2017 |               107|    3|           -6.2|          40|              0.9|             2000|                    -17.6|                       0|            0|             0|Winter  |No Holiday |Yes             |\n|01/12/2017 |                78|    4|           -6.0|          36|              2.3|             2000|                    -18.6|                       0|            0|             0|Winter  |No Holiday |Yes             |\n|01/12/2017 |               100|    5|           -6.4|          37|              1.5|             2000|                    -18.7|                       0|            0|             0|Winter  |No Holiday |Yes             |\n\n\n:::\n:::\n\n\nOn regarde combien de lignes possède le jeu de données.\n\n::: {.cell}\n\n```{.r .cell-code}\nnrow(seoul_bike)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 8760\n```\n\n\n:::\n:::\n\nIl y a 8760 observations, ce qui correspond à une observation par heure pendant \nune année (365 jours x 24 heures = 8760).\n\nOn va retirer les variables \"Date\" et \"Heure, qui ne sont pas \npertinentes pour notre analyse.\n\n::: {.cell}\n\n```{.r .cell-code}\nseoul_bike = seoul_bike %>% \n  select(-Date, -Hour)\nglimpse(seoul_bike)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nRows: 8,760\nColumns: 12\n$ Rented.Bike.Count        <int> 254, 204, 173, 107, 78, 100, 181, 460, 930, 4…\n$ Temperature.C.           <dbl> -5.2, -5.5, -6.0, -6.2, -6.0, -6.4, -6.6, -7.…\n$ Humidity...              <int> 37, 38, 39, 40, 36, 37, 35, 38, 37, 27, 24, 2…\n$ Wind.speed..m.s.         <dbl> 2.2, 0.8, 1.0, 0.9, 2.3, 1.5, 1.3, 0.9, 1.1, …\n$ Visibility..10m.         <int> 2000, 2000, 2000, 2000, 2000, 2000, 2000, 200…\n$ Dew.point.temperature.C. <dbl> -17.6, -17.6, -17.7, -17.6, -18.6, -18.7, -19…\n$ Solar.Radiation..MJ.m2.  <dbl> 0.00, 0.00, 0.00, 0.00, 0.00, 0.00, 0.00, 0.0…\n$ Rainfall.mm.             <dbl> 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, …\n$ Snowfall..cm.            <dbl> 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, …\n$ Seasons                  <fct> Winter, Winter, Winter, Winter, Winter, Winte…\n$ Holiday                  <fct> No Holiday, No Holiday, No Holiday, No Holida…\n$ Functioning.Day          <fct> Yes, Yes, Yes, Yes, Yes, Yes, Yes, Yes, Yes, …\n```\n\n\n:::\n:::\n\n\nLa variable \"Functioning.Day\" indique si le service de location de vélos est \nfonctionnel. On va retirer les jours où ce n'est pas le cas, car ils n'apportent\npas d'information pertinente pour notre analyse, puis retirer cette variable.\n\n::: {.cell}\n\n```{.r .cell-code}\nseoul_bike = seoul_bike %>%\n  filter(Functioning.Day == \"Yes\") %>%\n  select(-Functioning.Day)\n```\n:::\n\n\nOn observe maintenant nos variables restantes et notre nombre d'individus\n\n::: {.cell}\n\n```{.r .cell-code}\nglimpse(seoul_bike)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nRows: 8,465\nColumns: 11\n$ Rented.Bike.Count        <int> 254, 204, 173, 107, 78, 100, 181, 460, 930, 4…\n$ Temperature.C.           <dbl> -5.2, -5.5, -6.0, -6.2, -6.0, -6.4, -6.6, -7.…\n$ Humidity...              <int> 37, 38, 39, 40, 36, 37, 35, 38, 37, 27, 24, 2…\n$ Wind.speed..m.s.         <dbl> 2.2, 0.8, 1.0, 0.9, 2.3, 1.5, 1.3, 0.9, 1.1, …\n$ Visibility..10m.         <int> 2000, 2000, 2000, 2000, 2000, 2000, 2000, 200…\n$ Dew.point.temperature.C. <dbl> -17.6, -17.6, -17.7, -17.6, -18.6, -18.7, -19…\n$ Solar.Radiation..MJ.m2.  <dbl> 0.00, 0.00, 0.00, 0.00, 0.00, 0.00, 0.00, 0.0…\n$ Rainfall.mm.             <dbl> 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, …\n$ Snowfall..cm.            <dbl> 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, …\n$ Seasons                  <fct> Winter, Winter, Winter, Winter, Winter, Winte…\n$ Holiday                  <fct> No Holiday, No Holiday, No Holiday, No Holida…\n```\n\n\n:::\n\n```{.r .cell-code}\nnrow(seoul_bike)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 8465\n```\n\n\n:::\n:::\n\n\nLes deux variables \"Seasons\", \"Holiday\" sont catégorielles et il faudrait donc \nles transformer en variables numériques comme vu en cours. \nCependant, cette tâche s'effectue de manière automatique en R lorsque l'on \neffectue une régression . Il n'est donc pas nécessaire d'effectuer d'autres \npré-traitements.\n\n-----------------\n\n## Sélection du modèle de régression\n\nNotre regression va s'effectuer sur la variable cible \"Rented.Bike.Count\".\nOn commence par afficher le **matrice de corrélation** entre nos variables \nnumériques ce qui peut servir dans la sélection des variables. \n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Calculer la matrice de corrélation\ncor_matrix = cor(seoul_bike %>% select_if(is.numeric))\n# Afficher la matrice de corrélation\nkable(cor_matrix)\n```\n\n::: {.cell-output-display}\n\n\n|                         | Rented.Bike.Count| Temperature.C.| Humidity...| Wind.speed..m.s.| Visibility..10m.| Dew.point.temperature.C.| Solar.Radiation..MJ.m2.| Rainfall.mm.| Snowfall..cm.|\n|:------------------------|-----------------:|--------------:|-----------:|----------------:|----------------:|------------------------:|-----------------------:|------------:|-------------:|\n|Rented.Bike.Count        |         1.0000000|      0.5627402|  -0.2019727|        0.1250219|        0.2123228|                0.4002628|               0.2738616|   -0.1286261|    -0.1516108|\n|Temperature.C.           |         0.5627402|      1.0000000|   0.1664252|       -0.0384808|        0.0282621|                0.9144670|               0.3548435|    0.0521489|    -0.2177458|\n|Humidity...              |        -0.2019727|      0.1664252|   1.0000000|       -0.3373524|       -0.5485418|                0.5394024|              -0.4572727|    0.2369169|     0.1101265|\n|Wind.speed..m.s.         |         0.1250219|     -0.0384808|  -0.3373524|        1.0000000|        0.1804276|               -0.1771701|               0.3262219|   -0.0249313|    -0.0037893|\n|Visibility..10m.         |         0.2123228|      0.0282621|  -0.5485418|        0.1804276|        1.0000000|               -0.1825864|               0.1530461|   -0.1703518|    -0.1228597|\n|Dew.point.temperature.C. |         0.4002628|      0.9144670|   0.5394024|       -0.1771701|       -0.1825864|                1.0000000|               0.0985250|    0.1268125|    -0.1497598|\n|Solar.Radiation..MJ.m2.  |         0.2738616|      0.3548435|  -0.4572727|        0.3262219|        0.1530461|                0.0985250|               1.0000000|   -0.0741573|    -0.0733799|\n|Rainfall.mm.             |        -0.1286261|      0.0521489|   0.2369169|       -0.0249313|       -0.1703518|                0.1268125|              -0.0741573|    1.0000000|     0.0086041|\n|Snowfall..cm.            |        -0.1516108|     -0.2177458|   0.1101265|       -0.0037893|       -0.1228597|               -0.1497598|              -0.0733799|    0.0086041|     1.0000000|\n\n\n:::\n:::\n\n\nOn voit que la variable la plus corrélée (en valeur absolue) avec \"Rented.Bike.Count\" est \n\"Temperature.C.\" avec une valeur de 0.5627. C'est donc elle qu'il faudrait utiliser \npour effectuer une régression avec un seul prédicteur.\n\nEffectuons maintenant une régression multiple avec toutes les variables.\n\n::: {.cell}\n\n```{.r .cell-code}\n# Effectuer la régression multiple\nmodel_full = lm(Rented.Bike.Count ~ ., data = seoul_bike)\n# Afficher le résumé du modèle\nsummary(model_full)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nCall:\nlm(formula = Rented.Bike.Count ~ ., data = seoul_bike)\n\nResiduals:\n    Min      1Q  Median      3Q     Max \n-1521.6  -290.5   -51.6   200.2  2388.5 \n\nCoefficients:\n                           Estimate Std. Error t value Pr(>|t|)    \n(Intercept)              1095.58958  105.33805  10.401  < 2e-16 ***\nTemperature.C.             29.36879    3.99851   7.345 2.25e-13 ***\nHumidity...               -12.80340    1.12733 -11.357  < 2e-16 ***\nWind.speed..m.s.           65.63340    5.48185  11.973  < 2e-16 ***\nVisibility..10m.           -0.01392    0.01096  -1.270    0.204    \nDew.point.temperature.C.    6.39355    4.20086   1.522    0.128    \nSolar.Radiation..MJ.m2.  -121.41359    8.30863 -14.613  < 2e-16 ***\nRainfall.mm.              -51.73625    4.73360 -10.930  < 2e-16 ***\nSnowfall..cm.              52.24610   12.20140   4.282 1.87e-05 ***\nSeasonsSpring            -155.96574   15.37514 -10.144  < 2e-16 ***\nSeasonsSummer            -248.91432   18.74725 -13.277  < 2e-16 ***\nSeasonsWinter            -290.26902   21.53193 -13.481  < 2e-16 ***\nHolidayNo Holiday         142.71072   24.19296   5.899 3.80e-09 ***\n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\nResidual standard error: 471.3 on 8452 degrees of freedom\nMultiple R-squared:  0.4624,\tAdjusted R-squared:  0.4617 \nF-statistic: 605.9 on 12 and 8452 DF,  p-value: < 2.2e-16\n```\n\n\n:::\n:::\n\n\nSi on doit retirer du modèle une variable, on va regarder la plus grande valeur \npropre, il s'agit ici de (à part l'intercept que l'on ne va retirer) de \n\"Visibility..10m.\" (p-value = 0.204). On peut donc faire un \nnouveau modèle sans cette dernière.\n\n::: {.cell}\n\n```{.r .cell-code}\n# Régression sans \"Visibility..10m.\"\nmodel_refined = lm(Rented.Bike.Count ~ . - `Visibility..10m.`, \n                        data = seoul_bike)\n# Afficher le résumé du modèle\nsummary(model_refined)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nCall:\nlm(formula = Rented.Bike.Count ~ . - Visibility..10m., data = seoul_bike)\n\nResiduals:\n     Min       1Q   Median       3Q      Max \n-1500.09  -289.76   -50.88   200.20  2395.01 \n\nCoefficients:\n                         Estimate Std. Error t value Pr(>|t|)    \n(Intercept)              1048.929     98.730  10.624  < 2e-16 ***\nTemperature.C.             29.698      3.990   7.443 1.08e-13 ***\nHumidity...               -12.440      1.090 -11.408  < 2e-16 ***\nWind.speed..m.s.           65.034      5.462  11.907  < 2e-16 ***\nDew.point.temperature.C.    6.072      4.193   1.448    0.148    \nSolar.Radiation..MJ.m2.  -119.433      8.161 -14.634  < 2e-16 ***\nRainfall.mm.              -51.501      4.730 -10.888  < 2e-16 ***\nSnowfall..cm.              52.630     12.198   4.315 1.62e-05 ***\nSeasonsSpring            -151.615     14.989 -10.115  < 2e-16 ***\nSeasonsSummer            -250.539     18.704 -13.395  < 2e-16 ***\nSeasonsWinter            -284.918     21.117 -13.493  < 2e-16 ***\nHolidayNo Holiday         143.157     24.191   5.918 3.39e-09 ***\n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\nResidual standard error: 471.3 on 8453 degrees of freedom\nMultiple R-squared:  0.4623,\tAdjusted R-squared:  0.4616 \nF-statistic: 660.7 on 11 and 8453 DF,  p-value: < 2.2e-16\n```\n\n\n:::\n:::\n\n\nC'est maintenant \"Dew.point.temperature.C.\" qui a la plus grande p-valeur \n(0.148), on la retire également.\n\n::: {.cell}\n\n```{.r .cell-code}\n# Régression sans \"Visibility..10m.\" et \"Dew.point.temperature.C.\"\nmodel_refined = lm(Rented.Bike.Count ~ . - `Visibility..10m.` - \n                     `Dew.point.temperature.C.`, data = seoul_bike)\n# Afficher le résumé du modèle\nsummary(model_refined)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nCall:\nlm(formula = Rented.Bike.Count ~ . - Visibility..10m. - Dew.point.temperature.C., \n    data = seoul_bike)\n\nResiduals:\n     Min       1Q   Median       3Q      Max \n-1405.60  -292.24   -49.35   201.32  2397.89 \n\nCoefficients:\n                         Estimate Std. Error t value Pr(>|t|)    \n(Intercept)              916.0797    36.4638  25.123  < 2e-16 ***\nTemperature.C.            35.3176     0.9281  38.054  < 2e-16 ***\nHumidity...              -10.9346     0.3288 -33.252  < 2e-16 ***\nWind.speed..m.s.          64.7072     5.4574  11.857  < 2e-16 ***\nSolar.Radiation..MJ.m2. -122.0988     7.9516 -15.355  < 2e-16 ***\nRainfall.mm.             -52.3113     4.6972 -11.137  < 2e-16 ***\nSnowfall..cm.             51.2456    12.1613   4.214 2.54e-05 ***\nSeasonsSpring           -152.6058    14.9747 -10.191  < 2e-16 ***\nSeasonsSummer           -247.9027    18.6167 -13.316  < 2e-16 ***\nSeasonsWinter           -285.9263    21.1065 -13.547  < 2e-16 ***\nHolidayNo Holiday        142.7706    24.1914   5.902 3.74e-09 ***\n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\nResidual standard error: 471.4 on 8454 degrees of freedom\nMultiple R-squared:  0.4622,\tAdjusted R-squared:  0.4615 \nF-statistic: 726.5 on 10 and 8454 DF,  p-value: < 2.2e-16\n```\n\n\n:::\n:::\n\n\nTous les coefficients sont significatifs, on peut donc se satisfaire de ce \nmodèle.\n\n-----------------\n\n## Interprétations des résultats \n\nRegardons à nouveau le résumé de notre modèle affiné.\n\n::: {.cell}\n\n```{.r .cell-code}\nsummary(model_refined)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nCall:\nlm(formula = Rented.Bike.Count ~ . - Visibility..10m. - Dew.point.temperature.C., \n    data = seoul_bike)\n\nResiduals:\n     Min       1Q   Median       3Q      Max \n-1405.60  -292.24   -49.35   201.32  2397.89 \n\nCoefficients:\n                         Estimate Std. Error t value Pr(>|t|)    \n(Intercept)              916.0797    36.4638  25.123  < 2e-16 ***\nTemperature.C.            35.3176     0.9281  38.054  < 2e-16 ***\nHumidity...              -10.9346     0.3288 -33.252  < 2e-16 ***\nWind.speed..m.s.          64.7072     5.4574  11.857  < 2e-16 ***\nSolar.Radiation..MJ.m2. -122.0988     7.9516 -15.355  < 2e-16 ***\nRainfall.mm.             -52.3113     4.6972 -11.137  < 2e-16 ***\nSnowfall..cm.             51.2456    12.1613   4.214 2.54e-05 ***\nSeasonsSpring           -152.6058    14.9747 -10.191  < 2e-16 ***\nSeasonsSummer           -247.9027    18.6167 -13.316  < 2e-16 ***\nSeasonsWinter           -285.9263    21.1065 -13.547  < 2e-16 ***\nHolidayNo Holiday        142.7706    24.1914   5.902 3.74e-09 ***\n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\nResidual standard error: 471.4 on 8454 degrees of freedom\nMultiple R-squared:  0.4622,\tAdjusted R-squared:  0.4615 \nF-statistic: 726.5 on 10 and 8454 DF,  p-value: < 2.2e-16\n```\n\n\n:::\n:::\n\n\n### Significativité globale du modèle\n\nOn voit que le **R² ajusté** est de 0.4615, ce qui indique que le modèle explique\n46.15% de la variance totale de la variable cible \"Rented.Bike.Count\" \n(estimé sur la population). De plus, on voit sur la ligne suivante que le \n**test du F rejette l'hypothèse nulle** : \"le R² théorique est égal à zéro\" avec un \np-valeur < 2.2e-16, ce qui indique que le modèle est globalement très \nsignificatif.\n\n### Étude des coefficients\n\nSi on regarde maintenant les **coefficients**, on peut interpréter ceux-ci comme\nl'effet moyen d'une augmentation d'une unité de la variable explicative. \n\nOn a donc comme **effet positif** sur le nombre de location de vélos les variables :\n\n* Temperature.C.\n* Wind.speed..m.s.\n* Snowfall..cm.\n* La modalité \"No Holiday\" de la variable \"Holiday\" (il y a plus de vélos loués hors des vacances)\n\nEt comme **effet négatif** les variables :\n\n* Humidity....\n* Visibility..km.\n* La modalité \"Spring\" de la variable \"Seasons\"\n* La modalité \"Summer\" de la variable \"Seasons\"\n* La modalité \"Winter\" de la variable \"Seasons\"\n\nComme la modalité \"Autumn\" de la variable \"Seasons\" n'est pas présente dans le \nmodèle, c'est elle qui sert de référence pour les autres modalités. Les autres\nsaisons ayant un effet négatif, on en déduit que l'automne est la saison où il y \na le plus de locations de vélos en moyenne **à autres variables constantes**.\n\nPour voir l'**effet le plus important sans prendre en compte les unités**, on va\ncalculer les **coefficients standardisés** $\\beta$. \n\n::: {.cell}\n\n```{.r .cell-code}\n# Cet opération nécessite une librairie supplémentaire\nlibrary(QuantPsyc) \n```\n\n::: {.cell-output .cell-output-stderr}\n\n```\nLe chargement a nécessité le package : boot\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr}\n\n```\nLe chargement a nécessité le package : MASS\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr}\n\n```\n\nAttachement du package : 'MASS'\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr}\n\n```\nL'objet suivant est masqué depuis 'package:dplyr':\n\n    select\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr}\n\n```\n\nAttachement du package : 'QuantPsyc'\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr}\n\n```\nL'objet suivant est masqué depuis 'package:base':\n\n    norm\n```\n\n\n:::\n\n```{.r .cell-code}\n# Calculer les coefficients standardisés\nstandardized_coeffs = lm.beta::lm.beta(model_refined)\n# Afficher les coefficients standardisés\nkable(as.data.frame(standardized_coeffs$standardized.coefficients))\n```\n\n::: {.cell-output-display}\n\n\n|                        | standardized_coeffs$standardized.coefficients|\n|:-----------------------|---------------------------------------------:|\n|(Intercept)             |                                            NA|\n|Temperature.C.          |                                     0.6655204|\n|Humidity...             |                                    -0.3487079|\n|Wind.speed..m.s.        |                                     0.1041882|\n|Solar.Radiation..MJ.m2. |                                    -0.1650370|\n|Rainfall.mm.            |                                    -0.0916608|\n|Snowfall..cm.           |                                     0.0354265|\n|SeasonsSpring           |                                    -0.1035778|\n|SeasonsSummer           |                                    -0.1694689|\n|SeasonsWinter           |                                    -0.1940661|\n|HolidayNo Holiday       |                                     0.0476082|\n\n\n:::\n:::\n\n\nOn voit que la variable ayant l'effet standardisé le plus important est celui \nde \"Temperature.C.\" (0.6655), ce qui indique que c'est la variable la plus\nimportante pour expliquer le nombre de locations de vélos à Séoul. C'était \négalement la plus corrélée avec la variable cible.\n\n-----------------\n\n## Vérification des hypothèses de travail\n\nIl est important de vérifier que les hypothèses du modèle linéaire sont \nrespectées. On va donc regarder le diagramme des résidus.\n\n::: {.cell}\n\n```{.r .cell-code}\n# Obtenir les résidus du modèle et les valeurs prédites\nresiduals = model_refined$residuals\npredictied_values = model_refined$fitted.values\n# Tracer les résidus\nggplot() +\n  geom_point(aes(x = predictied_values, y = residuals)) +\n  geom_hline(yintercept = 0, linetype = \"dashed\", color = \"red\") +\n  labs(title = \"Résidus vs Valeurs Prédites\",\n       x = \"Valeurs Prédites\",\n       y = \"Résidus\")\n```\n\n::: {.cell-output-display}\n![](regression_seoulbike_files/figure-html/unnamed-chunk-12-1.png){width=672}\n:::\n:::\n\n\nCe graphique montre que qu'il n'y a pas une tendance non-linéaire particulière, la \n**linéarité est respectée**. En revanche, pour ce qui est de la **normalité et surtout \nl'homoscédasticité, ces hypothèses ne semblent pas être respectées**. Il faudra\ndonc mettre une certaine réserve dans la communication de nos résultats. \n\nLa forme particulière de ce graphique s'explique par le fait la variable cible\nne peut pas être négative (on ne peut pas louer un nombre négatif de vélos), ce qui\ncrée une sorte de \"limite\" pour les résidus négatifs. C'est ce qui rend ce modèle\nde régression moins fiable.\n\n-----------------\n\n\n\n\n\n\n",
    "supporting": [
      "regression_seoulbike_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}