{
  "hash": "746c30681306efbac36921a92c387658",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"IX. Le clustering\"\nauthor: \"Guillaume Guex\"\nnumber-sections: true\nlang: fr\n---\n\n## Introduction\n\nJusqu'à présent, nous avons cherché à expliquer une variable (la régression) ou à résumer l'information de plusieurs variables (les méthodes factorielles). Aujourd'hui, notre objectif est différent : nous voulons **découvrir des groupes homogènes d'individus** (des *clusters*) au sein de nos données, sans savoir à l'avance combien de groupes existent ni ce qu'ils représentent. C'est ce qu'on appelle la **classification non supervisée** ou **clustering**.\n\nNous allons voir ici deux méthodes de clustering : le **k-means** (k-moyennes en français) et la **Classification Ascendante Hiérarchique (CAH)**.\n\nLe clustering est extrêmement complémentaire avec les méthodes factorielles vues dans le cours précédent (ACP, MDS, AFC). En effet, l'ACP permet de réduire la dimensionnalité, d'éliminer le bruit et de créer une visualisation des individus, mais elle ne crée pas de \"frontières\" strictes entre les individus. À l'inverse, le clustering segmente les individus dans des classes discrètes, mais les résultats bruts sont difficiles à visualiser en haute dimension. La combinaison des deux donne souvent des résultats très parlants : on utilise l'ACP pour visualiser, puis le clustering pour catégoriser les individus.\n\nLes deux méthodes de clustering que nous allons étudier sont directement disponibles dans R. Nous allons charger ici `FactoMineR` afin de coupler notre clustering avec de la visualisation en basse dimensionnalité. De plus, `factoextra` possède des fonctions qui sont très utiles à la classification :\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(tidyverse)\nlibrary(FactoMineR)\nlibrary(factoextra)\nlibrary(aricode) # Pour l'indice AMI\n```\n:::\n\n\nComme les résultats du k-means sont en partie aléatoires (initialisation au hasard), nous allons ici fixer la \"graine aléatoire\" pour garantir la reproductibilité de nos analyses :\n\n\n::: {.cell}\n\n```{.r .cell-code}\nset.seed(2026)\n```\n:::\n\n\n## Le k-means\n\n### Théorie\n\nL'algorithme du **k-means**, ou des **k-moyennes** en français, est une méthode de partitionnement itérative. Son fonctionnement est assez intuitif à comprendre :\n\n1.  **Initialisation** : L'utilisateur choisit le nombre de groupes k. L'algorithme place aléatoirement k points (les \"centroïdes\") dans l'espace des données.\n2.  **Affectation** : Chaque individu est assigné au centroïde le plus proche (via la distance euclidienne), formant ainsi k groupes initiaux.\n3.  **Mise à jour** : L'algorithme recalcule la position exacte de chaque centroïde pour qu'il se place parfaitement au milieu (la moyenne) des individus de son groupe.\n4.  **Convergence** : Puisque les centroïdes ont bougé, on recommence l'étape 2. On boucle ainsi jusqu'à ce que plus aucun individu ne change de groupe.\n\n![Illustration du k-means](fig/k-means.png)\n\n### Le jeu de données\n\nNous allons utiliser le jeu de données `USArrests`, disponible nativement dans R, qui contient les taux d'arrestation pour divers crimes dans 50 États américains en 1973 :\n\n\n::: {.cell}\n\n```{.r .cell-code}\narrests_df = as_tibble(USArrests, rownames=\"Name\")\narrests_df\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 50 × 5\n   Name        Murder Assault UrbanPop  Rape\n   <chr>        <dbl>   <int>    <int> <dbl>\n 1 Alabama       13.2     236       58  21.2\n 2 Alaska        10       263       48  44.5\n 3 Arizona        8.1     294       80  31  \n 4 Arkansas       8.8     190       50  19.5\n 5 California     9       276       91  40.6\n 6 Colorado       7.9     204       78  38.7\n 7 Connecticut    3.3     110       77  11.1\n 8 Delaware       5.9     238       72  15.8\n 9 Florida       15.4     335       80  31.9\n10 Georgia       17.4     211       60  25.8\n# ℹ 40 more rows\n```\n\n\n:::\n:::\n\n\nPour enrichir notre future analyse, nous allons ajouter un jeu de données externe, issu d'une étude sur les orientations politiques des États US à travers le temps (<https://dataverse.harvard.edu/dataset.xhtml?persistentId=doi:10.7910/DVN/ZXZMJB>). Le jeu de données original (validation_data.csv, disponible dans le dossier data) a déjà été pré-traité pour obtenir quelques colonnes pertinentes pour notre analyse :\n\n\n::: {.cell}\n\n```{.r .cell-code}\nstates_meta_df = read_csv(\"data/states_meta_1973.csv\")\n```\n\n::: {.cell-output .cell-output-stderr}\n\n```\nRows: 50 Columns: 6\n── Column specification ────────────────────────────────────────────────────────\nDelimiter: \",\"\nchr (2): Name, region\ndbl (4): abortion, environment, gay_rights, families_payments\n\nℹ Use `spec()` to retrieve the full column specification for this data.\nℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.\n```\n\n\n:::\n:::\n\n\nOn effectue maintenant la jointure des données, sur la colonne `Name` qui contient le nom des États :\n\n\n::: {.cell}\n\n```{.r .cell-code}\nstates_df = arrests_df %>%\n  left_join(states_meta_df, by=\"Name\")\n```\n:::\n\n\nLes variables externes (non criminelles) vont nous servir de variables de comparaison pour interpréter les clusters que nous allons trouver. Cependant, ces clusters vont être calculés uniquement sur les variables de criminalité. La question sera : est-ce que les États qui ont des taux d'arrestation similaires ont aussi des orientations politiques ou géographiques similaires ?\n\nNous allons donc isoler les variables de criminalité pour faire le clustering. L'opération `column_to_rownames()` permet de conserver le nom des États comme identifiants de la matrice sans qu'ils soient considérés comme une variable numérique (et accessoirement, elle transforme le `tibble` en `dataframe`) :\n\n\n::: {.cell}\n\n```{.r .cell-code}\nclustering_df = states_df %>%\n  select(Name, Murder, Assault, UrbanPop, Rape) %>%\n  column_to_rownames(\"Name\")\n```\n:::\n\n\nDernier point (mais non des moindres) : il est absolument nécessaire de **standardiser** (centrer-réduire) les variables avant de faire des k-means ou une CAH. Sans cela, les variables avec les valeurs numériques les plus grandes (ici Assault qui monte à 337) prendront mathématiquement toute l'importance au détriment des autres variables (comme Murder qui est autour de 10) :\n\n\n::: {.cell}\n\n```{.r .cell-code}\nclustering_df = scale(clustering_df)\nhead(clustering_df)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n               Murder   Assault   UrbanPop         Rape\nAlabama    1.24256408 0.7828393 -0.5209066 -0.003416473\nAlaska     0.50786248 1.1068225 -1.2117642  2.484202941\nArizona    0.07163341 1.4788032  0.9989801  1.042878388\nArkansas   0.23234938 0.2308680 -1.0735927 -0.184916602\nCalifornia 0.27826823 1.2628144  1.7589234  2.067820292\nColorado   0.02571456 0.3988593  0.8608085  1.864967207\n```\n\n\n:::\n:::\n\n\n### Visualisation pré-clustering\n\nAvant d'effectuer le clustering, nous allons observer notre jeu de données avec une ACP :\n\n\n::: {.cell}\n\n```{.r .cell-code}\npca_res = PCA(clustering_df, graph=FALSE)\n```\n:::\n\n\nAffichons le screeplot :\n\n\n::: {.cell}\n\n```{.r .cell-code}\nfviz_eig(pca_res, addlabels=TRUE)\n```\n\n::: {.cell-output-display}\n![](Clustering_files/figure-html/unnamed-chunk-9-1.png){width=672}\n:::\n:::\n\n\nCe graphique nous montre que presque toute l'inertie (86.7%) se trouve sur les deux premiers axes. Le clustering que nous allons réaliser devrait donc être très bien représenté sur un plan en 2D.\n\nPassons au cercle des corrélations :\n\n\n::: {.cell}\n\n```{.r .cell-code}\nfviz_pca_var(pca_res, col.var=\"contrib\", \n             gradient.cols=c(\"#00AFBB\", \"#E7B800\", \"#FC4E07\"), \n             repel=TRUE)\n```\n\n::: {.cell-output-display}\n![](Clustering_files/figure-html/unnamed-chunk-10-1.png){width=672}\n:::\n:::\n\n\nL'axe 1 (horizontal) est principalement défini par les crimes violents (`Murder`, `Assault`, `Rape`), tandis que l'axe 2 (vertical) est principalement défini par l'urbanisation (`UrbanPop`).\n\nAffichons maintenant les individus sur les 4 premiers axes (dans notre cas, il s'agit de tous les axes disponibles) :\n\n\n::: {.cell}\n\n```{.r .cell-code}\nfviz_pca_ind(pca_res, repel=TRUE)\n```\n\n::: {.cell-output-display}\n![](Clustering_files/figure-html/unnamed-chunk-11-1.png){width=672}\n:::\n\n```{.r .cell-code}\nfviz_pca_ind(pca_res, axes=c(3, 4), repel=TRUE)\n```\n\n::: {.cell-output-display}\n![](Clustering_files/figure-html/unnamed-chunk-11-2.png){width=672}\n:::\n:::\n\n\nNous pouvons déjà utiliser une variable externe pour colorer nos points, en l'occurrence la région (à mettre dans `col.ind` si elle n'est pas présente dans le jeu de données qui a servi à l'ACP) :\n\n\n::: {.cell}\n\n```{.r .cell-code}\nfviz_pca_ind(pca_res, repel=TRUE, col.ind=states_df$region)\n```\n\n::: {.cell-output-display}\n![](Clustering_files/figure-html/unnamed-chunk-12-1.png){width=672}\n:::\n:::\n\n\nOn voit que cette dernier semble expliquer en partie la variance. Nous verrons plus loin si notre clustering va trouver des groupes similaires.\n\n### Détermination du nombre de groupes\n\nUne des grandes difficultés du k-means (et des méthodes de clustering en général) est de définir le nombre de groupes $k$ à priori. On peut pour cela s'aider de plusieurs indices mathématiques qui évaluent la qualité du clustering résultant. La librairie `factoextra` en propose trois.\n\n#### Le critère de la Silhouette\n\nL'*indice de la silhouette local* est calculé pour chaque point $i$, il s'agit de :\n$$  \\text{sil}_i = \\frac{b_i - a_i}{\\max(a_i, b_i)}$$\noù $a_i$ est la distance moyenne entre le point $i$ et les autres points de son propre cluster, et $b_i$ est la distance moyenne entre le point $i$ et les points du cluster le plus proche (celui auquel il n'appartient pas). Une valeur proche de 1 indique un point très bien classé, 0 un point ambigu, et -1 un point mal classé.\n\nL'*indice de la silhoutte global* est la moyenne de ces score de silouettes locaux :\n$$  \\text{sil} = \\frac{1}{n} \\sum_{i=1}^n \\text{sil}_i$$\n\nUtilise le critère de la silhouette consiste à sélectionner le nombre de groupes $k$ tel que cet indice soit maximal. On peut le faire aisémant avec la fonction `fviz_nbclust()` du package `factoextra` :\n\n\n::: {.cell}\n\n```{.r .cell-code}\nfviz_nbclust(clustering_df, kmeans) +\n  labs(title=\"Silhouette pour déterminer k\")\n```\n\n::: {.cell-output-display}\n![](Clustering_files/figure-html/unnamed-chunk-13-1.png){width=672}\n:::\n:::\n\n\nIci, la méthode de la silhouette nous suggère $k=2$.\n\n#### La méthode du coude sur l'inertie intra-groupe\n\nLe principe même du k-means est de minimiser l'inertie intra-groupe (WSS pour *Within-cluster Sum of Squares*), c'est-à-dire la somme des distances au carré entre les points et leur centroïde. En augmentant le nombre de groupes, on diminue forcément cette inertie, mais à un moment donné, l'amélioration devient marginale. La méthode du coude consiste à tracer l'inertie intra-groupe en fonction du nombre de groupes et à chercher le \"coude\" dans la courbe, c'est-à-dire le point où l'amélioration devient moins significative :\n\n\n::: {.cell}\n\n```{.r .cell-code}\nfviz_nbclust(clustering_df, kmeans, method=\"wss\") +\n  labs(title=\"Méthode du coude pour déterminer k\")\n```\n\n::: {.cell-output-display}\n![](Clustering_files/figure-html/unnamed-chunk-14-1.png){width=672}\n:::\n:::\n\n\nIci, le résultat semble faire apparaître un coude à $k=4$.\n\n#### La Gap statistic\n\nCette méthode compare l'inertie intra-groupe de vos données réelles avec celle d'une distribution de référence aléatoire sans aucune structure de cluster. L'algorithme génère des données uniformément réparties, effectue un cluserting, et calcule la moyenne du logarithme de l'inertie intra-groupe. Le \"Gap\" est la différence entre ce log(WSS) espéré et le log(WSS) observé sur vos vraies données.\n\nOn choisit la valeur de k qui maximise la statistique Gap. Plus précisément, l'algorithme sélectionne souvent la plus petite valeur de k pour laquelle le Gap est supérieur ou égal au Gap de k+1 moins son écart-type. C'est la méthode la plus robuste statistiquement des trois :\n\n\n::: {.cell}\n\n```{.r .cell-code}\nfviz_nbclust(clustering_df, kmeans, method=\"gap_stat\") +\n  labs(title=\"Gap statistic pour déterminer k\")\n```\n\n::: {.cell-output-display}\n![](Clustering_files/figure-html/unnamed-chunk-15-1.png){width=672}\n:::\n:::\n\n\nLa méthode suggère ici de prendre $k=2$, mais il y a aussi un pic significatif à $k=4$.\n\nCes trois critères montrent que le nombre de groupes optimal se situe entre 2 et 4. Nous allons opter ici pour **4 groupes**, pour avoir une granularité un peu plus intéressante qu'avec 2 groupes.\n\n### Résultats du k-means\n\nDans R, le k-means s'effectue avec la fonction `kmeans()` (nous l'avions déjà utilisée dans les arguements de `fviz_nbclust()`) :\n\n\n::: {.cell}\n\n```{.r .cell-code}\nkmeans_res = kmeans(clustering_df, centers=4, nstart=25)\n```\n:::\n\n\nL’argument `nstart=25` dit à R de faire 25 initialisations différentes du k-means et de garder le résultat avec la plus faible inertie intra-groupe. C'est une bonne pratique pour éviter de tomber sur un résultat sous-optimal.\n\nLe résultat de `kmeans()` contient plusieurs éléments, dont l'appartenance des points aux clusters. Pour voir ce que nous pouvons en extraire (comme souvent, avec `$`), il suffit d'afficher le résultat :\n\n\n::: {.cell}\n\n```{.r .cell-code}\nkmeans_res\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nK-means clustering with 4 clusters of sizes 13, 13, 16, 8\n\nCluster means:\n      Murder    Assault   UrbanPop        Rape\n1 -0.9615407 -1.1066010 -0.9301069 -0.96676331\n2  0.6950701  1.0394414  0.7226370  1.27693964\n3 -0.4894375 -0.3826001  0.5758298 -0.26165379\n4  1.4118898  0.8743346 -0.8145211  0.01927104\n\nClustering vector:\n       Alabama         Alaska        Arizona       Arkansas     California \n             4              2              2              4              2 \n      Colorado    Connecticut       Delaware        Florida        Georgia \n             2              3              3              2              4 \n        Hawaii          Idaho       Illinois        Indiana           Iowa \n             3              1              2              3              1 \n        Kansas       Kentucky      Louisiana          Maine       Maryland \n             3              1              4              1              2 \n Massachusetts       Michigan      Minnesota    Mississippi       Missouri \n             3              2              1              4              2 \n       Montana       Nebraska         Nevada  New Hampshire     New Jersey \n             1              1              2              1              3 \n    New Mexico       New York North Carolina   North Dakota           Ohio \n             2              2              4              1              3 \n      Oklahoma         Oregon   Pennsylvania   Rhode Island South Carolina \n             3              3              3              3              4 \n  South Dakota      Tennessee          Texas           Utah        Vermont \n             1              4              2              3              1 \n      Virginia     Washington  West Virginia      Wisconsin        Wyoming \n             3              3              1              1              3 \n\nWithin cluster sum of squares by cluster:\n[1] 11.952463 19.922437 16.212213  8.316061\n (between_SS / total_SS =  71.2 %)\n\nAvailable components:\n\n[1] \"cluster\"      \"centers\"      \"totss\"        \"withinss\"     \"tot.withinss\"\n[6] \"betweenss\"    \"size\"         \"iter\"         \"ifault\"      \n```\n\n\n:::\n:::\n\n\nEncore une fois, `factoextra` possède une fonction, nommée `fviz_cluster()`, qui permet de visualiser les résultats d'un clustering de manière pertinente. Cette fonction effectue automatiquement une ACP en arrière-plan pour projeter nos données dans le plan :\n\n\n::: {.cell}\n\n```{.r .cell-code}\nfviz_cluster(kmeans_res, data=clustering_df,\n             repel=TRUE\n)\n```\n\n::: {.cell-output-display}\n![](Clustering_files/figure-html/unnamed-chunk-18-1.png){width=672}\n:::\n:::\n\n\nCette fonction affiche les centroides et les frontières des groupes, tout ceci dans le plan factoriel. N'hésitez pas à consulter son aide pour voir toutes les possibilités qu'elle offre.\n\n### Liens entre les clusters et les variables\n\nUne (autre) des difficultés du clustering et de pouvoir interpréter ce que signifient et ce que contiennent les clusters trouvés. Si notre jeu de données est suffisamment petit, l'observation visuelle des clusters ou l'études de quelques indivus qui les composent peut suffire. Cependant, il est souvent nécessaire de faire une étude statistique complémentaire pour voir si les clusters sont liés ou non à différentes variables, qu'elles aient servi au clustering ou non. Nous allons faire cette étude ici.\n\nPour commencer, nous allons mettre le résultat du clustering dans notre jeu de données initial (dans la variable `clusters`), afin d'avoir toutes les données au même endroit :\n\n\n::: {.cell}\n\n```{.r .cell-code}\nstates_w_res_df = states_df %>%\n  mutate(clusters = factor(kmeans_res$cluster))\n```\n:::\n\n\n#### Liens entre clusters et variables numériques\n\nL'étude des liens entre clusters et variables numériques (utilisées pour le custering ou non) se fait en deux étapes :\n\n1.  On utilise un **test du F-ratio** (numérique x catégorielle) pour voir la **force du lien** ainsi que sa sifnificativité.\n\n2.  On étudie les **moyennes par groupe** des variables numériques pour voir les **profils types** de chaque groupe.\n\nConcernant les variables qui ont été utilisés dans le clustering, il y a de fortes chances qu'elles soient fortement liées à nos clusters. Cependant, on peut se demander si certaines ont été plus discriminantes que d'autres. On commence donc par faire des tests du F-ratio pour toutes les variables de criminalité :\n\n\n::: {.cell}\n\n```{.r .cell-code}\nsummary(aov(Murder ~ clusters, states_w_res_df))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n            Df Sum Sq Mean Sq F value   Pr(>F)    \nclusters     3  722.4   240.8   53.47 4.93e-15 ***\nResiduals   46  207.2     4.5                     \n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n```\n\n\n:::\n\n```{.r .cell-code}\nsummary(aov(Assault ~ clusters, states_w_res_df))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n            Df Sum Sq Mean Sq F value   Pr(>F)    \nclusters     3 266853   88951    55.7 2.38e-15 ***\nResiduals   46  73460    1597                     \n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n```\n\n\n:::\n\n```{.r .cell-code}\nsummary(aov(UrbanPop ~ clusters, states_w_res_df))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n            Df Sum Sq Mean Sq F value   Pr(>F)    \nclusters     3   6002  2000.7   21.58 7.14e-09 ***\nResiduals   46   4264    92.7                     \n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n```\n\n\n:::\n\n```{.r .cell-code}\nsummary(aov(Rape ~ clusters, states_w_res_df))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n            Df Sum Sq Mean Sq F value   Pr(>F)    \nclusters     3   3022  1007.3   36.29 3.48e-12 ***\nResiduals   46   1277    27.8                     \n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n```\n\n\n:::\n:::\n\n\nOn observe que toutes ces variables ont un lien très significatif (p valeur infime). Cependant, il apparait que les variables `Assault` (F=55.7) et `Murder` (F=53.47) ont un pouvoir discriminant plus grand que `Rape` (F=36.29) et `UrbanPop` (F=21.58).\n\nLe même test effectué sur des variables supplémentaires nous donne :\n\n\n::: {.cell}\n\n```{.r .cell-code}\nsummary(aov(abortion ~ clusters, states_w_res_df))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n            Df Sum Sq Mean Sq F value Pr(>F)  \nclusters     3  160.5   53.49   2.495 0.0716 .\nResiduals   46  986.0   21.44                 \n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n```\n\n\n:::\n\n```{.r .cell-code}\nsummary(aov(environment ~ clusters, states_w_res_df))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n            Df Sum Sq Mean Sq F value Pr(>F)\nclusters     3  284.8   94.94   1.691  0.182\nResiduals   46 2581.9   56.13               \n```\n\n\n:::\n\n```{.r .cell-code}\nsummary(aov(gay_rights ~ clusters, states_w_res_df))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n            Df Sum Sq Mean Sq F value Pr(>F)  \nclusters     3  0.899  0.2995   2.935 0.0432 *\nResiduals   46  4.695  0.1021                 \n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n```\n\n\n:::\n\n```{.r .cell-code}\nsummary(aov(families_payments ~ clusters, states_w_res_df))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n            Df  Sum Sq Mean Sq F value Pr(>F)   \nclusters     3  835394  278465   6.424  0.001 **\nResiduals   46 1993865   43345                  \n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n```\n\n\n:::\n:::\n\n\nCette fois-ci, on voit que seule `families_payments` (p=0.001) et, dans un moindre mesure, `gay_rights` (p=0.043) sont significatives. Les autres orientations politiques testées ne semblent pas liées à nos profils de criminalité.\n\nPour déterminer maintenant les profils concrets des États dans les différents clusters, ont va s'intéresser aux moyennes de ces variables au seins des différents groupes (on affiche également le nombre d'individus par cluster, pour avoir un profil plus complet) :\n\n\n::: {.cell}\n\n```{.r .cell-code}\nstates_w_res_df %>%\n  group_by(clusters) %>%\n  summarise(n = n(),\n            m_Murder = mean(Murder),\n            m_Assault = mean(Assault),\n            m_UrbanPop = mean(UrbanPop),\n            m_Rape = mean(Rape), \n            m_fpayments = mean(families_payments))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 4 × 7\n  clusters     n m_Murder m_Assault m_UrbanPop m_Rape m_fpayments\n  <fct>    <int>    <dbl>     <dbl>      <dbl>  <dbl>       <dbl>\n1 1           13     3.6       78.5       52.1   12.2        852.\n2 2           13    10.8      257.        76     33.2        831.\n3 3           16     5.66     139.        73.9   18.8        889.\n4 4            8    13.9      244.        53.8   21.4        512.\n```\n\n\n:::\n:::\n\n\nPour résumer succintement :\n\n| Cluster | Murder | Assault | UrbanPop | Rape   | Payment |\n|---------|--------|---------|----------|--------|---------|\n| 1       | faible | moyen   | élevé    | moyen  | élevé   |\n| 2       | élevé  | élevé   | élevé    | élevé  | élevé   |\n| 3       | élevé  | élevé   | faible   | moyen  | faible  |\n| 4       | faible | faible  | faible   | faible | élevé   |\n\nCe qui illustre bien nos différents groupes.\n\n#### Liens entre clusters et variables catégorielles\n\nPour voir les liens entre nos clusters et des variables catégorielles externes (liens entre variables catégorielles-catégorielles), il s'agira de construire une **table de contingence** et d'effectuer un **test du chi2**. Nous allons vérifier ici si nos clusters ont un lien avec la variable `region`.\n\nOn commence par construire la table de contingence :\n\n\n::: {.cell}\n\n```{.r .cell-code}\nregion_clust = states_w_res_df %>%\n  select(region, clusters) %>%\n  table()\nregion_clust\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n             clusters\nregion        1 2 3 4\n  midatlantic 0 2 3 0\n  midwest     2 2 2 0\n  newengland  3 0 3 0\n  plains      6 4 3 0\n  south       2 2 2 8\n  west        0 3 3 0\n```\n\n\n:::\n:::\n\n\nPuis on fait un test du chi2 :\n\n\n::: {.cell}\n\n```{.r .cell-code}\nchisq.test(region_clust)\n```\n\n::: {.cell-output .cell-output-stderr}\n\n```\nWarning in chisq.test(region_clust): L’approximation du Chi-2 est peut-être\nincorrecte\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n\tPearson's Chi-squared test\n\ndata:  region_clust\nX-squared = 36.037, df = 15, p-value = 0.001746\n```\n\n\n:::\n:::\n\n\nLe test est significatif (p \\< 0.05), il existe bien un lien entre les clusters de criminalité et la région. On voit par exemple que le cluster 3 contient uniquement des États du sud, ce qui corrobore notre profilage (forte criminalité et faible population urbaine typique des États du Sud à cette époque).\n\nLes liens entre variables catégorielles peuvent aussi être mesurés à l'aide d'indices issus de la **théorie de l'information**, généralement basés sur l'**information mutuelle**. Il en existe plusieurs, contenus pour la plupart dans la package `aricode`. Nous allons calculer ici le `AMI` (*Adjusted Mutual Information*) entre `clusters` et `region`. C'est un indice standardisé et corrigé (pour tenir compte du hasard), compris entre 0 (aucun lien) et 1 (partitions identiques) :\n\n\n::: {.cell}\n\n```{.r .cell-code}\nAMI(as.factor(states_w_res_df$region), states_w_res_df$clusters)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 0.1399376\n```\n\n\n:::\n:::\n\n\nLe valeur de AMI=0.14 indique un lien mais faible, ce qui est cohérent avec le test du chi2 qui, bien que significatif, montre que les clusters ne sont pas complètement déterminés par la région.\n\n## La Classification ascendante hiérarchique (CAH)\n\nContrairement au k-means qui force à fixer $k$ dès le départ, la **Classification ascendante hiérarchique (CAH)** propose une approche différente, qui se base sur une matrice de dissimilarité entre individus calculée en amont :\n\n1.  Au départ, chaque individu est considéré comme son propre groupe (ici, 50 groupes).\n\n2.  L'algorithme cherche les deux individus les plus proches (dissimilarité minimale) et les fusionne.\n\n3.  Les distances sont recalculées entre le nouveau groupe formé et les autres individus restants, en fonction d'un critère de liaison (p.ex. : saut minimal, saut maximal, méthode de Ward).\n\n4.  L'algorithme boucle sur l'étape 2 et 3 jusqu'à ce que tous les individus soient agglomérés dans un seul groupe.\n\nLe résultat final illustre toutes les étapes de cet algorithme sous la forme d'un arbre de classification hiérarchique : le **dendrogramme**, que l'on peut a posteriori couper à la hauteur désirée pour obtenir nos groupes.\n\n### Application de la CAH\n\nOn commence par calculer la matrice des dissimilarités entre individus (ici, la distance euclidienne entre les variables standardisées) :\n\n\n::: {.cell}\n\n```{.r .cell-code}\ndist_mat = dist(clustering_df, method=\"euclidean\")\n```\n:::\n\n\nLa CAH s'effectue ensuite avec la fonction `hclust()`, qui prend en argument la matrice de dissimilarité et le critère de liaison. Nous utilisons ici `\"ward.D2\"` : à chaque étape, la méthode de Ward fusionne les deux groupes qui feront augmenter le moins possible la variance intra-groupe. Elle a tendance à créer des clusters compacts :\n\n\n::: {.cell}\n\n```{.r .cell-code}\ncah_res = hclust(dist_mat, method=\"ward.D2\")\n```\n:::\n\n\nSi notre jeu de données et de taille raisonnable, on peut ensuite visualiser le dendrogramme avec `fviz_dend()` :\n\n\n::: {.cell}\n\n```{.r .cell-code}\nfviz_dend(cah_res, cex=0.5, \n          main=\"Dendrogramme de la CAH (Méthode de Ward)\")\n```\n\n::: {.cell-output-display}\n![](Clustering_files/figure-html/unnamed-chunk-28-1.png){width=672}\n:::\n:::\n\n\n### Détermination du nombre de groupes\n\nLa question est maintenant de savoir où couper cet arbre. La longueur verticale des branches représente la distance (l'hétérogénéité) entre les groupes fusionnés. On cherche généralement à couper l'arbre au niveau des branches les plus longues. Mais on peut aussi utiliser les critères vus précédemment.\n\nNous allons utiliser ici la méthode de la silhouette avec `fviz_nbclust()` (en lui passant l'argument FUN=hcut pour qu'il utilise une CAH au lieu du k-means) :\n\n\n::: {.cell}\n\n```{.r .cell-code}\nfviz_nbclust(clustering_df, FUN=hcut, method=\"silhouette\") +\n  labs(title=\"Silhouette pour déterminer le nombre optimal de clusters\")\n```\n\n::: {.cell-output-display}\n![](Clustering_files/figure-html/unnamed-chunk-29-1.png){width=672}\n:::\n:::\n\n\nAvec ce critère, le nombre de groupes optimal est $k=2$. On peut afficher le dendrogramme avec cette coupe dans `fviz_dend()`:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nfviz_dend(cah_res, k=2, \n          cex=0.5, \n          color_labels_by_k=TRUE, \n          rect=TRUE,\n          main=\"Dendrogramme coupé en 2 groupes\")\n```\n\n::: {.cell-output-display}\n![](Clustering_files/figure-html/unnamed-chunk-30-1.png){width=672}\n:::\n:::\n\n\nPour extraire les groupes dans un vecteur, on utilise la fonction `cutree()` la hauteur correspondant à $k=2$ :\n\n\n::: {.cell}\n\n```{.r .cell-code}\ngrps_cah = cutree(cah_res, k=2)\n```\n:::\n\n\n### Liens entre les clusters et les variables\n\nComme pour le résultat du k-means, nous allons rapidement étudier les liens entre ces nouveaux clusters et nos variables. Il sera particulièrement intéressant de comparer le clustering obetnu avec la CAH (k=2) avec celui obtenu avec le k-means (k=4).\n\nOn commence par ajouter ces nouveaux clusters dans notre jeu de données étendu :\n\n\n::: {.cell}\n\n```{.r .cell-code}\nstates_w_res_df = states_w_res_df %>%\n  mutate(clusters2 = factor(grps_cah))\n```\n:::\n\n\nOn calcule les F-ratios entre ces 2 clusters CAH et les variables numériques :\n\n\n::: {.cell}\n\n```{.r .cell-code}\nsummary(aov(Murder ~ clusters2, states_w_res_df))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n            Df Sum Sq Mean Sq F value   Pr(>F)    \nclusters2    1  632.6   632.6   102.3 1.75e-13 ***\nResiduals   48  296.9     6.2                     \n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n```\n\n\n:::\n\n```{.r .cell-code}\nsummary(aov(Assault ~ clusters2, states_w_res_df))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n            Df Sum Sq Mean Sq F value   Pr(>F)    \nclusters2    1 240323  240323   115.4 2.32e-14 ***\nResiduals   48  99990    2083                     \n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n```\n\n\n:::\n\n```{.r .cell-code}\nsummary(aov(UrbanPop ~ clusters2, states_w_res_df))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n            Df Sum Sq Mean Sq F value Pr(>F)\nclusters2    1    236   236.1    1.13  0.293\nResiduals   48  10030   209.0               \n```\n\n\n:::\n\n```{.r .cell-code}\nsummary(aov(Rape ~ clusters2, states_w_res_df))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n            Df Sum Sq Mean Sq F value   Pr(>F)    \nclusters2    1   1953  1953.3   39.98 8.04e-08 ***\nResiduals   48   2345    48.9                     \n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n```\n\n\n:::\n\n```{.r .cell-code}\nsummary(aov(abortion ~ clusters2, states_w_res_df))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n            Df Sum Sq Mean Sq F value Pr(>F)\nclusters2    1    0.8   0.826   0.035  0.853\nResiduals   48 1145.7  23.868               \n```\n\n\n:::\n\n```{.r .cell-code}\nsummary(aov(environment ~ clusters2, states_w_res_df))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n            Df Sum Sq Mean Sq F value Pr(>F)\nclusters2    1   16.7   16.73   0.282  0.598\nResiduals   48 2850.0   59.37               \n```\n\n\n:::\n\n```{.r .cell-code}\nsummary(aov(gay_rights ~ clusters2, states_w_res_df))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n            Df Sum Sq Mean Sq F value Pr(>F)\nclusters2    1  0.138  0.1380   1.214  0.276\nResiduals   48  5.456  0.1137               \n```\n\n\n:::\n\n```{.r .cell-code}\nsummary(aov(families_payments ~ clusters2, states_w_res_df))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n            Df  Sum Sq Mean Sq F value Pr(>F)  \nclusters2    1  180759  180759   3.276 0.0766 .\nResiduals   48 2648500   55177                 \n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n```\n\n\n:::\n:::\n\n\nCurieusement, en séparant les données en seulement 2 grands groupes, la variable `UrbanPop` n'est plus du tout significative (p=0.29). Les deux groupes se sont formés purement sur l'axe de la criminalité. De plus, aucune des variables externes n'est significative à ce niveau de granularité.\n\nRegardons les moyennes des variables criminelles pour ces deux clusters :\n\n\n::: {.cell}\n\n```{.r .cell-code}\nstates_w_res_df %>%\n  group_by(clusters2) %>%\n  summarise(n = n(),\n            m_Murder = mean(Murder),\n            m_Assault = mean(Assault),\n            m_Rape = mean(Rape))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 2 × 5\n  clusters2     n m_Murder m_Assault m_Rape\n  <fct>     <int>    <dbl>     <dbl>  <dbl>\n1 1            19    12.3       259.   29.2\n2 2            31     5.00      116.   16.3\n```\n\n\n:::\n:::\n\n\nCes deux grands clusters séparent de manière évidente et binaire les États avec une très forte criminalité globale (groupe 1) des États avec une faible criminalité (groupe 2).\n\nRegardons s'il y a un lien entre la CAH et la variable région :\n\n\n::: {.cell}\n\n```{.r .cell-code}\nregion_clust2 = states_w_res_df %>%\n  select(region, clusters2) %>%\n  table()\nregion_clust2\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n             clusters2\nregion         1  2\n  midatlantic  2  3\n  midwest      2  4\n  newengland   0  6\n  plains       3 10\n  south        9  5\n  west         3  3\n```\n\n\n:::\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nchisq.test(region_clust2)\n```\n\n::: {.cell-output .cell-output-stderr}\n\n```\nWarning in chisq.test(region_clust2): L’approximation du Chi-2 est peut-être\nincorrecte\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n\tPearson's Chi-squared test\n\ndata:  region_clust2\nX-squared = 9.4427, df = 5, p-value = 0.09266\n```\n\n\n:::\n\n```{.r .cell-code}\nAMI(as.factor(states_w_res_df$region), states_w_res_df$clusters2)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 0.0350692\n```\n\n\n:::\n:::\n\n\nLe lien n'est pas significatif et l'information mutuelle ajustée est très faible. La région géographique est donc un mauvais prédicteur de cette séparation binaire.\n\nPour finir, comparons nos deux méthodologies de partitionnement :\n\n\n::: {.cell}\n\n```{.r .cell-code}\nclust_clust= states_w_res_df %>%\n  select(clusters, clusters2) %>%\n  table()\nclust_clust\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n        clusters2\nclusters  1  2\n       1  0 13\n       2 12  1\n       3  0 16\n       4  7  1\n```\n\n\n:::\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nchisq.test(clust_clust)\n```\n\n::: {.cell-output .cell-output-stderr}\n\n```\nWarning in chisq.test(clust_clust): L’approximation du Chi-2 est peut-être\nincorrecte\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n\tPearson's Chi-squared test\n\ndata:  clust_clust\nX-squared = 42.368, df = 3, p-value = 3.352e-09\n```\n\n\n:::\n\n```{.r .cell-code}\nAMI(as.factor(states_w_res_df$clusters), as.factor(states_w_res_df$clusters2))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 0.3778938\n```\n\n\n:::\n:::\n\n\nLe lien est très fort (AMI = 0.38, p-value microscopique). En observant la table de contingence, on constate que la CAH a agi comme une \"méta-classification\" des k-means : les clusters 1 et 4 des k-means sont complètement inclus dans le macro-cluster 2 de la CAH, et à deux exceptions près, les clusters 2 et 3 du k-means forment le macro-cluster 1 de la CAH.\n\n## AFC et Clustering sur des données textuelles\n\nComme vu dans le cours précédant, Une matrice document-terme est généralement immense et l'AFC permet de résumer efficacement les profils des documents. Cependant, nous avons vu que les régions du biplot n'étaient pas si facile à interpréter au niveau des termes, car ceux-ci sont très nombreux et difficile à afficher simultanément.\n\nUne des solutions à ce problème consiste à utiliser les coordonnées factorielles sur les termes pour faire un **clustering sur les termes**, afin d'associer les mots utilisés conjointement par plusieurs documents. Ce clustering nous permet ensuite de décrire certaines régions du biplot.\n\nCette approche a de forts liens avec le domaine du **topic modeling** en NLP, qui cherche à trouver des \"thèmes\" ou \"topics\" dans un corpus de textes. Nos clusters de termes trouvés par cette méthode peuvent être interprétés comme des thèmes récurrents dans les documents.\n\nNous allons utiliser ici la matrice document-terme `manifesto_dtf.csv`, déjà utilisée lors du cours précédant, qui contient les manifestes politiques de 9 partis politiques français écrits en 2017.\n\n### L'AFC\n\nOn charge la matrice document-terme :\n\n\n::: {.cell}\n\n```{.r .cell-code}\ndtf = read_csv(\"data/manifesto_dtf.csv\") %>%\n  column_to_rownames(\"doc_id\") \n```\n\n::: {.cell-output .cell-output-stderr}\n\n```\nRows: 9 Columns: 7567\n── Column specification ────────────────────────────────────────────────────────\nDelimiter: \",\"\nchr    (1): doc_id\ndbl (7566): emmanuel, macron, président, retrouver, esprit, conquête, bâtir,...\n\nℹ Use `spec()` to retrieve the full column specification for this data.\nℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.\n```\n\n\n:::\n\n```{.r .cell-code}\nas_tibble(dtf)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 9 × 7,566\n  emmanuel macron président retrouver esprit conquête bâtir france nouvelle\n     <dbl>  <dbl>     <dbl>     <dbl>  <dbl>    <dbl> <dbl>  <dbl>    <dbl>\n1        1      1         3         2      4        2     2     21        5\n2        0      0         0         1      0        0     0     38        2\n3        0      2         6         2      5        0     1     64       18\n4        0      0         0         2      1        0     1     36        2\n5        0      0         4         2      1        0     4     36       10\n6        0      1         1         0      0        0     0      0        1\n7        0      0         6         0      0        2     0     21        6\n8        0      0         0         0      0        0     0      7        0\n9        2      2         2         1      2        0     0     35        6\n# ℹ 7,557 more variables: contrat <dbl>, nation <dbl>, programme <dbl>,\n#   construit <dbl>, vivre <dbl>, travail <dbl>, inventer <dbl>,\n#   nouvelles <dbl>, protections <dbl>, sommes <dbl>, condamnés <dbl>,\n#   choisir <dbl>, chômage <dbl>, masse <dbl>, précarisation <dbl>,\n#   naïfs <dbl>, savons <dbl>, vie <dbl>, progrès <dbl>, personnel <dbl>,\n#   collectif <dbl>, dépend <dbl>, effort <dbl>, appelle <dbl>, lorsqu <dbl>,\n#   pratiqué <dbl>, bonnes <dbl>, conditions <dbl>, correctement <dbl>, …\n```\n\n\n:::\n:::\n\n\nPuis on effectue l'AFC, avec, comme vu la dernière fois, le document `parti_communiste_francais` comme ligne supplémentaire :\n\n\n::: {.cell}\n\n```{.r .cell-code}\nca_res = CA(dtf + 1e-50, graph=F, row.sup=6)\n```\n:::\n\n\nOn affiche ensuite le biplot avec les 30 mots les plus contributifs sur les 2 premiers axes :\n\n\n::: {.cell}\n\n```{.r .cell-code}\nfviz_ca_biplot(ca_res, repel=T, select.col=list(contrib=30))\n```\n\n::: {.cell-output-display}\n![](Clustering_files/figure-html/unnamed-chunk-41-1.png){width=672}\n:::\n:::\n\n\n### La CAH sur les termes\n\nPour faire le clustering sur les termes, on va utiliser les coordonnées factorielles des termes sur les 2 premiers axes de l'AFC. Ces coordonnées résument bien la position de chaque terme dans l'espace factoriel et le fait de ne pas toutes les prendre permet d'éliminer en grande partie le \"bruit\" présent dans les données :\n\n\n::: {.cell}\n\n```{.r .cell-code}\nword_coords = ca_res$col$coord[, 1:2]\n```\n:::\n\n\nOn effectue cette fois le clustering hiérachique avec la fonction `HCPC()` du package `FactoMineR`, qui est une fonction très pratique pour faire du clustering hiérarchique sur des données factorielles. L'argument `nb.clust=-1` dit à la fonction de déterminer automatiquement le nombre optimal de clusters (selon un critère maison, voir l'aide) :\n\n\n::: {.cell}\n\n```{.r .cell-code}\nhcpc_res = HCPC(as.data.frame(word_coords), nb.clust = -1, graph = FALSE)\nclust_grp = hcpc_res$data.clust$clust\n```\n:::\n\n\nOn examine la taille des différents clusters :\n\n\n::: {.cell}\n\n```{.r .cell-code}\ntable(clust_grp)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nclust_grp\n   1    2    3    4 \n 902 1883 3393 1388 \n```\n\n\n:::\n:::\n\n\nCependant, si l'on essaye de les visualiser, il y a trop de termes présents pour comprendre le résultat :\n\n\n::: {.cell}\n\n```{.r .cell-code}\nfviz_cluster(hcpc_res,\n             show.clust.cent = TRUE,\n             ggtheme = theme_minimal(),\n             main = \"Clustering Sémantique\",\n             labelsize=5\n)\n```\n\n::: {.cell-output-display}\n![](Clustering_files/figure-html/unnamed-chunk-45-1.png){width=672}\n:::\n:::\n\n\n### Caractérisation des clusters et affichage\n\nPour caractériser les clusters, on peut regarder les termes qui les composent, et en particulier les termes les plus proches des centres (les plus \"typiques\").\n\nOn commence par calculer les coordonnées des centroïdes de chaque cluster (la fonction `aggregate()` permet de calculer une fonction par groupe) :\n\n\n::: {.cell}\n\n```{.r .cell-code}\ncentroids = aggregate(word_coords, by=list(cluster=clust_grp), FUN=mean)\n```\n:::\n\n\nOn calcule maintenant, de manière optimisée pour éviter les boucles (les fonctions de type `apply()` sont fondamentales pour faire du R optimisé sans boucle, mais c'est un sujet avancé), la distance de chaque terme à son centroïde de cluster. On extrait ensuite les 10 termes les plus proches :\n\n\n::: {.cell}\n\n```{.r .cell-code}\nn_words = 10\nclosest_words = lapply(1:nrow(centroids), function(i) {\n  cluster_center = as.numeric(centroids[i, -1])\n  distances = apply(word_coords, 1, function(word) sqrt(sum((word - cluster_center)^2)))\n  closest_indices = order(distances)[1:n_words]\n  return(names(distances)[closest_indices])\n})\n```\n:::\n\n\nCela nous permet d'avoir une liste des mots les plus typique par groupe :\n\n\n::: {.cell}\n\n```{.r .cell-code}\nclosest_words\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[[1]]\n [1] \"nets\"           \"savons\"         \"engagerons\"     \"combattrons\"   \n [5] \"véhicule\"       \"imposerons\"     \"interdirons\"    \"généraliserons\"\n [9] \"diminuerons\"    \"lancerons\"     \n\n[[2]]\n [1] \"constituante\" \"réaliser\"     \"arrêter\"      \"proposons\"    \"monarchie\"   \n [6] \"méditerranée\" \"alliance\"     \"suivantes\"    \"abroger\"      \"humain\"      \n\n[[3]]\n [1] \"petites\"      \"débit\"        \"redressement\" \"attente\"      \"liberté\"     \n [6] \"fasse\"        \"produit\"      \"mandature\"    \"small\"        \"nommer\"      \n\n[[4]]\n [1] \"propose\"      \"compétence\"   \"activement\"   \"comportant\"   \"del\"         \n [6] \"toutefois\"    \"presidentiel\" \"affectation\"  \"portant\"      \"budgetaire\"  \n```\n\n\n:::\n:::\n\n\nOn met tous ces mots dans un vecteur pour pouvoir les afficher sur le biplot :\n\n\n::: {.cell}\n\n```{.r .cell-code}\nall_words = unique(unlist(closest_words))\n```\n:::\n\n\nToutes ces étapes permettent de visualiser notre biplot avec des \"directions sémantiques\" plus claires, grâce à l'affichage des mots les plus typiques de chaque cluster :\n\n\n::: {.cell}\n\n```{.r .cell-code}\nfviz_ca_biplot(ca_res, \n               geom.row=\"text\",\n               col.col=clust_grp,\n               repel=T, \n               select.col=list(name=all_words), \n               labelsize = 3\n)\n```\n\n::: {.cell-output-display}\n![](Clustering_files/figure-html/unnamed-chunk-50-1.png){width=672}\n:::\n:::\n\n\nUne alternative aurait été d'afficher les 50 mots les plus contributifs et de les colorer par cluster, ce qui est moins couteux au niveau des calculs. Cependant, les mots choisis sont représentatifs du plan factoriel et non pas des clusters :\n\n\n::: {.cell}\n\n```{.r .cell-code}\nfviz_ca_biplot(ca_res, \n               geom.row=\"text\",\n               col.col=clust_grp,\n               repel=T, \n               select.col=list(contrib=50), \n               labelsize = 3\n)\n```\n\n::: {.cell-output-display}\n![](Clustering_files/figure-html/unnamed-chunk-51-1.png){width=672}\n:::\n:::\n\n",
    "supporting": [
      "Clustering_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}