{
  "hash": "df764fe392750c81c74511cda4f5dc12",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"VII. La régression linéaire et logistique\"\nauthor: \"Guillaume Guex\"\nnumber-sections: true\nlang: fr\n---\n\n## Introduction et Préparation des données\n\nDans ce cours, nous allons voir comment faire des modèles de **régression linéaire multiple** et de **régression logistique** avec R. Une troisième partie va également s'intéresser aux stratégies de **sélection de modèles**, applicables aussi bien à la régression linéaire qu'à la régression logistique.\n\nLes fonctions fondamentales pour faire ces modèles, qui sont **`lm()`** et **`glm()`**, sont déjà présentes dans la base de R. Cependant de nombreuses extensions proposent des résultats, diagnostiques et procédures supplémentaires qui s'avèrent très utiles. Les packages nécessaires pour cette session sont donc les suivants :\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(tidyverse)\nlibrary(ISLR2) # Contient le jeu de données `Wage` sur lequel nous allons travailler\nlibrary(broom) # Pour extraire les résultats des modèles de manière \"tidy\"\nlibrary(car) # Pour un test global sur les variables catégorielles\nlibrary(MuMIn) # Pour la sélection de modèles exhaustive\n```\n:::\n\n\nTout au long de ce cours, nous allons utiliser le jeu de données `Wage` du package `ISLR`. Il contient les informations salariales et démographiques de 3000 travailleurs masculins de la région \"Mid-Atlantic\" aux États-Unis.\n\nCommençons par le charger, transformons-le en tibble, et examinons-le :\n\n\n::: {.cell}\n\n```{.r .cell-code}\nwage_df = as_tibble(Wage)\nwage_df\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 3,000 × 11\n    year   age maritl  race  education region jobclass health health_ins logwage\n   <int> <int> <fct>   <fct> <fct>     <fct>  <fct>    <fct>  <fct>        <dbl>\n 1  2006    18 1. Nev… 1. W… 1. < HS … 2. Mi… 1. Indu… 1. <=… 2. No         4.32\n 2  2004    24 1. Nev… 1. W… 4. Colle… 2. Mi… 2. Info… 2. >=… 2. No         4.26\n 3  2003    45 2. Mar… 1. W… 3. Some … 2. Mi… 1. Indu… 1. <=… 1. Yes        4.88\n 4  2003    43 2. Mar… 3. A… 4. Colle… 2. Mi… 2. Info… 2. >=… 1. Yes        5.04\n 5  2005    50 4. Div… 1. W… 2. HS Gr… 2. Mi… 2. Info… 1. <=… 1. Yes        4.32\n 6  2008    54 2. Mar… 1. W… 4. Colle… 2. Mi… 2. Info… 2. >=… 1. Yes        4.85\n 7  2009    44 2. Mar… 4. O… 3. Some … 2. Mi… 1. Indu… 2. >=… 1. Yes        5.13\n 8  2008    30 1. Nev… 3. A… 3. Some … 2. Mi… 2. Info… 1. <=… 1. Yes        4.72\n 9  2006    41 1. Nev… 2. B… 3. Some … 2. Mi… 2. Info… 2. >=… 1. Yes        4.78\n10  2004    52 2. Mar… 1. W… 2. HS Gr… 2. Mi… 2. Info… 2. >=… 1. Yes        4.86\n# ℹ 2,990 more rows\n# ℹ 1 more variable: wage <dbl>\n```\n\n\n:::\n:::\n\n\nCe jeu de données est déjà très propre, il n'y a donc pas beaucoup de pré-traitements à effectuer. Cependant, avec de nombreuses méthodes statistiques en R, dont les modèles de régression, définir le bon **type** des variables (numériques, catégorielles, ordinales) est très important, car les calculs effectués de manière sous-jacente ne seront pas les mêmes.\n\nIci, les variables catégorielles sont déjà correctement typées. Il nous reste à formater les variables ordinales, ce qui est facile à faire ici car, comme elles commencent par des numéros, l'ordre alphabétique correspond naturellement à l'ordre hiérarchique (sinon, on aurait dû définir l'ordre via le vecteur donné dans l'argument `levels`) :\n\n\n::: {.cell}\n\n```{.r .cell-code}\nwage_df = wage_df %>%\n  mutate(\n    education = factor(education, ordered=T),\n    health = factor(health, ordered=T)\n  )\nhead(wage_df$education)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 1. < HS Grad    4. College Grad 3. Some College 4. College Grad\n[5] 2. HS Grad      4. College Grad\n5 Levels: 1. < HS Grad < 2. HS Grad < 3. Some College < ... < 5. Advanced Degree\n```\n\n\n:::\n\n```{.r .cell-code}\nhead(wage_df$health)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 1. <=Good      2. >=Very Good 1. <=Good      2. >=Very Good 1. <=Good     \n[6] 2. >=Very Good\nLevels: 1. <=Good < 2. >=Very Good\n```\n\n\n:::\n:::\n\n\nNous le verrons plus tard, mais dans le cadre de la régression, les variables ordinales sont traitées de manière très particulière, à mi-chemin entre des variables numériques et des variables catégorielles. Nous allons créer deux autres versions de ces dernières, une numérique et une catégorielle, qui nous permettront de les intégrer dans les modèles de régression d'une manière ciblée :\n\n\n::: {.cell}\n\n```{.r .cell-code}\nwage_df = wage_df %>%\n  mutate(\n    education_num = as.numeric(education),\n    education_cat = factor(education, ordered=F),\n    health_num = as.numeric(health),\n    health_cat = factor(health, ordered=F)\n  )\nhead(wage_df$education_num)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 1 4 3 4 2 4\n```\n\n\n:::\n\n```{.r .cell-code}\nhead(wage_df$education_cat)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 1. < HS Grad    4. College Grad 3. Some College 4. College Grad\n[5] 2. HS Grad      4. College Grad\n5 Levels: 1. < HS Grad 2. HS Grad 3. Some College ... 5. Advanced Degree\n```\n\n\n:::\n:::\n\n\n## La régression linéaire\n\n### Théorie (rappel)\n\nLa régression linéaire (multiple) est un modèle qui postule qu'une variable numérique $Y$, appelée **variable dépendante** ou **critère**, peut s'exprimer en fonction de $p$ autres variables numériques $X_1, \\ldots X_p$, appelées **variables indépendantes** ou **prédicteurs**, selon la formule suivante : $$  \nY = b_0 + b_1 X_1 + b_2 X_2 + \\ldots + b_p X_p + \\epsilon\n$$ où les $b_i$ sont les **coefficients de régression**, $b_0$ est l'**ordonnée à l'origine** ou l'**intercept**, et $\\epsilon$ représente le **terme d'erreur** ou le **résidu** (c'est-à-dire la part de $Y$ qui n'est pas expliquée par les variables indépendantes).\n\nCette relation est dite **linéaire** car elle suppose qu'il y a une structure sous-jacente de type \"hyperplan\", autrement dit une droite dans la cas de la régression simple :\n\n\n::: {.cell}\n\n```{.r .cell-code}\nx = runif(50)\ny = 2 + 3 * x + rnorm(50, sd=0.5)\ndf = tibble(x, y)\nggplot(df, aes(x=x, y=y)) +\n  geom_point() +\n  geom_abline(intercept=2, slope=3, color=\"red\", linetype=\"dashed\")\n```\n\n::: {.cell-output-display}\n![](Regression_files/figure-html/unnamed-chunk-5-1.png){width=672}\n:::\n:::\n\n\nOn trouve les coefficients de régression par la méthode des **moindres carrés ordinaires** (OLS). L'algorithme va chercher l'unique droite qui minimise l'**erreur carrée moyenne** (MSE), c'est-à-dire qui minimise la distance verticale entre chaque point réel $y_i$ et la prédiction du modèle $\\hat{y}_i$ : $$\n  \\text{MSE} = \\tfrac{1}{n} \\sum_{i=1}^{n} (y_i - \\hat{y}_i)^2\n$$ avec $\\hat{y}_i = b_0 + b_1 x_{i1} + \\ldots + b_p x_{ip}$.\n\n### Construire un modèle linéaire avec `lm()`\n\nUn **modèle linéaire** s'obtient avec la fonction `lm()` de R. Cette dernière demande comme premier argument une **formule** qui a une structure particulière et qui utilise l'opérateur tilde `~`.\n\nLa structure usuelle d'une formule est la suivante :\n\n```         \n<variable réponse> ~ <variable 1> + <variable 2> + ... + <variable p>\n```\n\nMais on peut également utiliser d'autres syntaxes :\n\n-   En utilisant `<variable réponse> ~ .`, on indique que l'on prédit avec toutes les variables du jeu de données.\n-   En ajoutant `-1` à la formule, la droite de régression passera par l'origine (on omet l'intercept).\n-   `<variable i>^n` permet d'ajouter l'ordre $n$ de la variable\n-   `<variable i>*<variable j>` permet d'ajouter les termes d'interaction.\n-   Plusieurs fonctions peuvent être utilisées sur les variables, comme `exp()` ou `log()`.\n\nDans le jeu de données `Wage`, l'objectif sera de prédire la variable `wage` (le salaire annuel en milliers de \\$) en fonction d'autres variables du jeu de données. Pour commencer, nous allons faire un modèle linéaire en utilisant simplement deux autres variables numériques, `age` et `education_num` :\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlm_res = lm(wage ~ age + education_num, data=wage_df)\n```\n:::\n\n\nNous avons sauvegardé le résultat dans la variable `lm_res`, car il s'agit d'une sortie qui est utilisable dans plusieurs contextes (une manière de travailler fréquente en R). En premier lieu, cette sortie s'utilise avec `summary()`, qui donne de nombreuses informations sur la régression effectuée :\n\n\n::: {.cell}\n\n```{.r .cell-code}\nsummary(lm_res)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nCall:\nlm(formula = wage ~ age + education_num, data = wage_df)\n\nResiduals:\n     Min       1Q   Median       3Q      Max \n-104.286  -19.796   -3.664   14.659  220.625 \n\nCoefficients:\n              Estimate Std. Error t value Pr(>|t|)    \n(Intercept)   38.77503    2.90509   13.35   <2e-16 ***\nage            0.58847    0.05723   10.28   <2e-16 ***\neducation_num 15.93645    0.54341   29.33   <2e-16 ***\n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\nResidual standard error: 36.08 on 2997 degrees of freedom\nMultiple R-squared:  0.2527,\tAdjusted R-squared:  0.2522 \nF-statistic: 506.8 on 2 and 2997 DF,  p-value: < 2.2e-16\n```\n\n\n:::\n:::\n\n\nExaminons cette sortie :\n\n-   **Call:** donne la formule utilisée.\n-   **Residuals:** donne un aperçu de la distribution des résidus, qui devraient suivre une distribution normale centrée autour de zéro pour que les hypothèses du modèle soient respectées.\n-   **Coefficients:** donne les estimations des coefficients de régression, leur erreur standard, la statistique $t$ et la valeur $p$ associée. Ces valeurs permettent de tester l'hypothèse nulle selon laquelle le coefficient est égal à zéro (c'est-à-dire que la variable n'a pas d'effet sur la variable dépendante).\n-   **En bas:** on trouve plusieurs statistiques globales du modèle, comme le $R^2$ et le $R^2$-ajusté, qui permettent d'évaluer sa qualité globale.\n\nOn voit que ce modèle explique environ 25% de la variance totale des salaires, que l'intercept et nos deux coefficients sont significatifs, et que les deux variables associées ont un effet positif sur le salaire.\n\nNotez que l'on peut extraire plusieurs informations de ce résultat via l'opérateur `$` :\n\n\n::: {.cell}\n\n```{.r .cell-code}\nnames(lm_res)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n [1] \"coefficients\"  \"residuals\"     \"effects\"       \"rank\"         \n [5] \"fitted.values\" \"assign\"        \"qr\"            \"df.residual\"  \n [9] \"xlevels\"       \"call\"          \"terms\"         \"model\"        \n```\n\n\n:::\n:::\n\n\nComme par exemple, les coefficients de régression :\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlm_res$coefficients\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n  (Intercept)           age education_num \n   38.7750345     0.5884726    15.9364472 \n```\n\n\n:::\n:::\n\n\nSi l'on cherche à faire des **prédictions** à l'aide de ce modèle, on peut utiliser la fonction `predict()`, qui prend en argument la variable contenant le modèle ainsi qu'un nouveau jeu de données (avec des variables ayant le même nom que celles utilisées pour construire le modèle) :\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Les nouvelles données avec 2 individus\nnew_df = tibble(age=c(30, 40), education_num=c(2, 4))\n# La prédiction du salaire sur ces nouveaux individus\npredict(lm_res, new_df)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n        1         2 \n 88.30211 126.05973 \n```\n\n\n:::\n:::\n\n\n### Extraire les résultats avec `broom`\n\nBien que `summary()` soit un standard historique, sa sortie est du texte brut, difficilement manipulable dans un \"pipeline\" d'opérations. Au sain du `tidyverse`, c'est le package `broom` qui s'utilise pour transformer les sorties statistiques complexes de plusieurs modèles en tableaux de données propres (des tibbles).\n\nPour les **coefficents** de régression, on utilise la fonction \\``tidy()` :\n\n\n::: {.cell}\n\n```{.r .cell-code}\ntidy(lm_res)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 3 × 5\n  term          estimate std.error statistic   p.value\n  <chr>            <dbl>     <dbl>     <dbl>     <dbl>\n1 (Intercept)     38.8      2.91        13.3 1.61e- 39\n2 age              0.588    0.0572      10.3 2.14e- 24\n3 education_num   15.9      0.543       29.3 1.98e-166\n```\n\n\n:::\n:::\n\n\nPour les **métriques globales** du modèle, on utilise la fonction `glance()`, qui donne un résumé de la qualité du modèle :\n\n\n::: {.cell}\n\n```{.r .cell-code}\nglance(lm_res)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 1 × 12\n  r.squared adj.r.squared sigma statistic   p.value    df  logLik    AIC    BIC\n      <dbl>         <dbl> <dbl>     <dbl>     <dbl> <dbl>   <dbl>  <dbl>  <dbl>\n1     0.253         0.252  36.1      507. 2.57e-190     2 -15013. 30034. 30058.\n# ℹ 3 more variables: deviance <dbl>, df.residual <int>, nobs <int>\n```\n\n\n:::\n:::\n\n\nNous nous pencherons plus en détails sur ces critères dans la @sec-select, consacrée à la sélection des modèles.\n\nPour les **résidus** et les **prédictions** du modèle, on utilise la fonction `augment()`, qui ajoute des colonnes au jeu de données original (avec uniquement les variables retenues) avec les valeurs ajustées, les résidus, et d'autres diagnostics :\n\n\n::: {.cell}\n\n```{.r .cell-code}\naugment(lm_res)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 3,000 × 9\n    wage   age education_num .fitted .resid     .hat .sigma   .cooksd .std.resid\n   <dbl> <int>         <dbl>   <dbl>  <dbl>    <dbl>  <dbl>     <dbl>      <dbl>\n 1  75.0    18             1    65.3   9.74 0.00258    36.1   6.30e-5      0.270\n 2  70.5    24             4   117.  -46.2  0.00147    36.1   8.05e-4     -1.28 \n 3 131.     45             3   113.   17.9  0.000350   36.1   2.88e-5      0.497\n 4 155.     43             4   128.   26.9  0.000555   36.1   1.03e-4      0.745\n 5  75.0    50             2   100.  -25.0  0.000735   36.1   1.18e-4     -0.694\n 6 127.     54             4   134.   -7.18 0.000854   36.1   1.13e-5     -0.199\n 7 170.     44             3   112.   57.1  0.000340   36.1   2.83e-4      1.58 \n 8 112.     30             3   104.    7.48 0.000721   36.1   1.03e-5      0.207\n 9 119.     41             3   111.    8.17 0.000338   36.1   5.79e-6      0.227\n10 129.     52             2   101.   27.4  0.000829   36.1   1.60e-4      0.761\n# ℹ 2,990 more rows\n```\n\n\n:::\n:::\n\n\nOn peut ainsi facilement visualiser le **diagramme des résidus**, qui permet de vérifier visuellement les hypothèses de notre modèle (homoscédasticité, linéarité et normalité) :\n\n\n::: {.cell}\n\n```{.r .cell-code}\nggplot(augment(lm_res)) +\n  geom_point(aes(x=.fitted, y=.resid)) +\n  geom_hline(yintercept=0, color=\"red\", linetype=\"dashed\") +\n  labs(title = \"Graphique des Résidus vs Valeurs Prédites\",\n       x = \"Salaire Prédit\",\n       y = \"Résidus\")\n```\n\n::: {.cell-output-display}\n![](Regression_files/figure-html/unnamed-chunk-14-1.png){width=672}\n:::\n:::\n\n\nCes hypothèses semblent vérifiées ici (les erreurs sont à peu près symétriques autour de la ligne rouge).\n\n### Les prédicteurs catégoriels ou ordinaux\n\nIl est possible d'intégrer directement des variables catégorielles ou ordinales dans un modèle de régression linéaire, en tant que **prédicteurs**, et R va les traiter automatiquement de la manière la plus adéquate possible.\n\n#### Les variables catégorielles dans le modèle linéaire\n\nQue se passe-t-il lorsque nous incluons dans notre fonction `lm()` une variable catégorielle comme `maritl`, qui contient 5 modalités ?\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlevels(wage_df$maritl)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] \"1. Never Married\" \"2. Married\"       \"3. Widowed\"       \"4. Divorced\"     \n[5] \"5. Separated\"    \n```\n\n\n:::\n:::\n\n\nR gère cela grâce à un processus appelé **Dummy Encoding** (ou création de variables indicatrices). Si une variable catégorielle possède $m$ modalités, R va créer $m-1$ nouvelles variables binaires (contenant uniquement des 0 et des 1).\n\nLa raison pour laquelle R crée $m-1$ modalités au lieu de $m$ est qu'il faut éviter la redondance parfaite d'information dans le jeu de données, et si l'on ajoute toutes les colonnes, l'une d'elle est déductible des $m-1$ autres. Pour éviter cela, R enlève toujours une modalité qui devient la **catégorie de référence** (par défaut, la première dans l'ordre alphabétique, ou la première définie dans le `factor`). Cette catégorie de référence est comme \"absorbée\" par l'intercept et les coefficients des autres modalités représentent donc la **différence par rapport à cette catégorie de référence**.\n\nPour voir exactement le tableau de données que R construit avant d'ajuster le modèle linéaire, nous pouvons utiliser la fonction `model.matrix()` :\n\n\n::: {.cell}\n\n```{.r .cell-code}\ndummies_encoding = model.matrix(wage ~ maritl, wage_df)\nhead(dummies_encoding, 10)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n   (Intercept) maritl2. Married maritl3. Widowed maritl4. Divorced\n1            1                0                0                 0\n2            1                0                0                 0\n3            1                1                0                 0\n4            1                1                0                 0\n5            1                0                0                 1\n6            1                1                0                 0\n7            1                1                0                 0\n8            1                0                0                 0\n9            1                0                0                 0\n10           1                1                0                 0\n   maritl5. Separated\n1                   0\n2                   0\n3                   0\n4                   0\n5                   0\n6                   0\n7                   0\n8                   0\n9                   0\n10                  0\n```\n\n\n:::\n:::\n\n\nSi l'on ajoute donc cette variable catégorielle `maritl` dans le modèle précédent, on obtient :\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlm_res = lm(wage ~ age + education_num + maritl, wage_df)\nsummary(lm_res)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nCall:\nlm(formula = wage ~ age + education_num + maritl, data = wage_df)\n\nResiduals:\n     Min       1Q   Median       3Q      Max \n-107.750  -19.353   -3.366   14.555  217.848 \n\nCoefficients:\n                   Estimate Std. Error t value Pr(>|t|)    \n(Intercept)        36.88259    2.85355  12.925  < 2e-16 ***\nage                 0.33591    0.06277   5.351  9.4e-08 ***\neducation_num      15.61140    0.53445  29.210  < 2e-16 ***\nmaritl2. Married   18.79420    1.76767  10.632  < 2e-16 ***\nmaritl3. Widowed    1.22593    8.30134   0.148  0.88261    \nmaritl4. Divorced   4.98086    2.98850   1.667  0.09568 .  \nmaritl5. Separated 13.28207    5.02192   2.645  0.00822 ** \n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\nResidual standard error: 35.33 on 2993 degrees of freedom\nMultiple R-squared:  0.2848,\tAdjusted R-squared:  0.2834 \nF-statistic: 198.6 on 6 and 2993 DF,  p-value: < 2.2e-16\n```\n\n\n:::\n:::\n\n\nAttention cependant à l'interprétation. Ici, seul les niveaux `Married` et `Separated` sont significatifs, mais **en référence au niveau `Never Married`**. Le salaire des personnes de ces deux catégories est donc significativement différent par rapport aux personnes n'ayant jamais été mariées. Pour les autres statuts maritaux, l'échantillon ne permet pas de prouver qu'ils gagnent significativement plus ou moins que les gens n'ayant jamais été mariés.\n\nPour tester si la variable `maritl` a un impact global sur le modèle (malgré le fait que certaines de ses modalités ne soient pas significatives), la bonne pratique consiste à faire une analyse de variance avec la fonction `Anova()` du package `car` :\n\n\n::: {.cell}\n\n```{.r .cell-code}\nAnova(lm_res)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nAnova Table (Type II tests)\n\nResponse: wage\n               Sum Sq   Df F value    Pr(>F)    \nage             35734    1  28.636 9.395e-08 ***\neducation_num 1064746    1 853.245 < 2.2e-16 ***\nmaritl         167436    4  33.544 < 2.2e-16 ***\nResiduals     3734899 2993                      \n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n```\n\n\n:::\n:::\n\n\nIci, la valeur p très faible de `maritl` nous confirme que le statut marital, dans son ensemble, est une variable pertinente à conserver dans notre modèle.\n\nPour avoir d'autres contrastes, il est possible de changer le niveau de référence d'une variable avec `relevel()` :\n\n\n::: {.cell}\n\n```{.r .cell-code}\nrlv_wage_df = wage_df %>%\n  mutate(maritl = relevel(maritl, ref=\"2. Married\"))\nlm_res = lm(wage ~ age + education_num + maritl, rlv_wage_df)\nsummary(lm_res)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nCall:\nlm(formula = wage ~ age + education_num + maritl, data = rlv_wage_df)\n\nResiduals:\n     Min       1Q   Median       3Q      Max \n-107.750  -19.353   -3.366   14.555  217.848 \n\nCoefficients:\n                        Estimate Std. Error t value Pr(>|t|)    \n(Intercept)             55.67679    3.28002  16.975  < 2e-16 ***\nage                      0.33591    0.06277   5.351 9.40e-08 ***\neducation_num           15.61140    0.53445  29.210  < 2e-16 ***\nmaritl1. Never Married -18.79420    1.76767 -10.632  < 2e-16 ***\nmaritl3. Widowed       -17.56828    8.15103  -2.155   0.0312 *  \nmaritl4. Divorced      -13.81334    2.59989  -5.313 1.16e-07 ***\nmaritl5. Separated      -5.51213    4.84299  -1.138   0.2551    \n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\nResidual standard error: 35.33 on 2993 degrees of freedom\nMultiple R-squared:  0.2848,\tAdjusted R-squared:  0.2834 \nF-statistic: 198.6 on 6 and 2993 DF,  p-value: < 2.2e-16\n```\n\n\n:::\n:::\n\n\n#### Les variables ordinales dans le modèle linéaire\n\nPour ces variables, on sait qu'il y a un ordre, mais **on ne sait pas si les écarts entre les modalités sont tous équivalents**. R les traite de manière assez particulière.\n\nPrenons directement un exemple avec la variable `education` (ordinale cette fois). Si l'on crée un modèle avec cette dernière, on obtient :\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlm_res = lm(wage ~ age + education, wage_df)\nsummary(lm_res)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nCall:\nlm(formula = wage ~ age + education, data = wage_df)\n\nResiduals:\n     Min       1Q   Median       3Q      Max \n-110.033  -19.635   -3.907   14.441  220.408 \n\nCoefficients:\n            Estimate Std. Error t value Pr(>|t|)    \n(Intercept) 88.40777    2.53789  34.835  < 2e-16 ***\nage          0.56869    0.05719   9.943  < 2e-16 ***\neducation.L 50.05925    1.86518  26.839  < 2e-16 ***\neducation.Q  8.13375    1.74709   4.656 3.37e-06 ***\neducation.C  2.63428    1.43992   1.829   0.0674 .  \neducation^4  0.61756    1.36837   0.451   0.6518    \n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\nResidual standard error: 35.94 on 2994 degrees of freedom\nMultiple R-squared:  0.2593,\tAdjusted R-squared:  0.2581 \nF-statistic: 209.6 on 5 and 2994 DF,  p-value: < 2.2e-16\n```\n\n\n:::\n:::\n\n\nOn voit que cette variable été incluse avec **différentes tendances**, résumées par les indications `L`, `Q`, `C` et `^4` :\n\n-   **Tendance Linéaire `L`** : le modèle teste s'il y a une tendance linéaire globale. Autrement dit, on regarde si le fait de monter d'un niveau de diplôme augmente le salaire de manière régulière et constante.\n\n-   **Tendance Quadratique `Q`** : le modèle teste s'il y a une courbure (une forme en \"U\"). Ici, la supposition est que les petits diplômes ne changent pas beaucoup le salaire, mais que l'effet augmente lorsque l'on arrive au Master ou au Doctorat.\n\n-   **Tendance Cubique `C`** : le modèle teste s'il y a deux courbures (une forme en \"S\"). En gros, est-ce qu'on a un gros gain avec les premiers diplômes, puis un plateau (stagnation), puis de nouveau un gros gain avec les plus hauts diplômes.\n\n-   **Tendance Quartique** `^4` : au-delà du cubique, les niveaux deviennent difficiles à interpréter et l'on a presque intérêt à traiter la variable comme une variable catégorielle sans ordre.\n\nIl peut parfois être préférable d'utiliser les versions purement numériques ou catégorielles de cette variable, car l'interprétation s'en trouve allégée. D'une manière générale, si le `L` est le principal facteur significatif, alors la relation est presque linéaire et on peut utiliser sa version numérique. À l'inverse, si les tendances d'ordres supérieurs (cubique, quartique) sont les seules à être très significatives, la relation d'ordre devient difficile à interpréter et il est peut-être préférable de considérer la variable comme une variable catégorielle non-ordinale.\n\n## La régression logistique\n\n### Théorie\n\nJusqu'à présent, nous avons cherché à prédire le salaire (`wage`), qui est une variable numérique continue. Mais que se passe-t-il si nous voulons prédire une **variable catégorielle binaire** $Y$ (0 ou 1, Oui ou Non, Succès ou Échec) ?\n\nImaginons que nous voulions prédire si un travailleur a un salaire considéré comme \"élevé\" (que nous définirons arbitrairement à plus de 120 000\\$ par an). Créons cette variable :\n\n\n::: {.cell}\n\n```{.r .cell-code}\nwage_df = wage_df %>%\n  mutate(high_wage = ifelse(wage > 120, 1, 0))\n# On regarde les proportions de chaque catégorie dans le jeu de données\ntable(wage_df$high_wage) \n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n   0    1 \n2047  953 \n```\n\n\n:::\n:::\n\n\nSi nous utilisons une régression linéaire classique (`lm()`) pour modéliser cette variable binaire, nous faisons face à un problème : une droite infinie finira inévitablement par prédire des valeurs absurdes, c'est-à-dire négatives ou supérieures à 1 (100%).\n\nPour résoudre ce problème, la régression logistique n'utilise pas une droite, mais une courbe en forme de \"S\" **la fonction sigmoïde**, notée $\\sigma()$, qui s'applique sur la formule de régression pour prédire une probabilité : $$\n  P(Y = 1) = \\sigma(b_0 + b_1 X_1 + b_2 X_2 + \\ldots + b_p X_p + \\epsilon) \n$$\n\nLa fonction sigmoïde se définit comme : $$\n\\sigma(z) = \\frac{1}{1 + e^{-z}}\n$$ et transforme n'importe quelle valeur réelle $z$ en une valeur comprise entre 0 et 1, interprétable comme une probabilité. On le voit avec sa courbe :\n\n\n::: {.cell}\n\n```{.r .cell-code}\nx = seq(-10, 10, length.out=100)\ny = 1 / (1 + exp(-x))\ndf = tibble(x, y)\nggplot(df, aes(x=x, y=y)) +\n  geom_line(color=\"blue\") +\n  labs(title=\"Fonction Sigmoïde\",\n       x=\"x\",\n       y=\"sigmoid(x)\")\n```\n\n::: {.cell-output-display}\n![](Regression_files/figure-html/unnamed-chunk-22-1.png){width=672}\n:::\n:::\n\n\nEn réalité, on peut aussi voir la régression logistique comme une modélisation des **log-odds** (le logarithme du rapport des probabilités) de la variable dépendante avec une relation linéaire : $$\n\\ln\\left(\\frac{P(Y=1)}{1 - P(Y=1)}\\right) = b_0 + b_1 X_1 + b_2 X_2 + \\ldots + b_p X_p\n$$ Nous le verrons plus tard, cette manière de poser le problème permet de mieux interpréter les coefficients de la régression logistique.\n\nNotez que la régression logistique ne minimise pas les moindres carrées pour trouver les coefficients de régression, mais une **entropie relative entre les probabilités prédites et les probabilités réelles** (i.e. la variable binaire). À cause de cela, sa résolution algorithmique est plus lente.\n\n### Construire un modèle de régression logistique avec `glm()`\n\nEn R, nous n'utilisons plus `lm()`, mais `glm()` (pour *Generalized Linear Model*). La syntaxe de la formule est exactement la même, mais nous devons ajouter l'argument `family=\"binomial\"` pour indiquer à R d'utiliser la transformation logistique.\n\nEssayons de prédire la probabilité d'avoir un haut salaire en fonction de l'âge et du niveau d'éducation (version numérique) :\n\n\n::: {.cell}\n\n```{.r .cell-code}\nglm_res = glm(high_wage ~ age + education_num, wage_df, family=\"binomial\")\nsummary(glm_res)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nCall:\nglm(formula = high_wage ~ age + education_num, family = \"binomial\", \n    data = wage_df)\n\nCoefficients:\n               Estimate Std. Error z value Pr(>|z|)    \n(Intercept)   -4.950826   0.231505 -21.385  < 2e-16 ***\nage            0.032059   0.003975   8.065 7.35e-16 ***\neducation_num  0.871085   0.040084  21.732  < 2e-16 ***\n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\n(Dispersion parameter for binomial family taken to be 1)\n\n    Null deviance: 3750.6  on 2999  degrees of freedom\nResidual deviance: 3083.6  on 2997  degrees of freedom\nAIC: 3089.6\n\nNumber of Fisher Scoring iterations: 4\n```\n\n\n:::\n:::\n\n\nCe qui change fondamentalement ici, c'est l'**interprétation des coefficients de régression**. Si vous regardez la colonne `Estimate`, ces chiffres expriment une *variation dans les log-odds* par rapport à la référence définie par l'intercept (-4.95). Pour rendre ces coefficients interprétables, nous devons annuler le logarithme en appliquant une fonction exponentielle, qui nous donne alors des **odds ratios**, ou en français, des **rapports de cotes**.\n\nLe package `broom` est ici très utile car la fonction `tidy()` possède un argument (`exponentiate=T`) qui les calcule automatiquement :\n\n\n::: {.cell}\n\n```{.r .cell-code}\ntidy(glm_res, exponentiate=T, conf.int=T)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 3 × 7\n  term          estimate std.error statistic   p.value conf.low conf.high\n  <chr>            <dbl>     <dbl>     <dbl>     <dbl>    <dbl>     <dbl>\n1 (Intercept)    0.00708   0.232      -21.4  1.83e-101  0.00447    0.0111\n2 age            1.03      0.00398      8.06 7.35e- 16  1.02       1.04  \n3 education_num  2.39      0.0401      21.7  1.03e-104  2.21       2.59  \n```\n\n\n:::\n:::\n\n\nLa colonne estimate contient désormais les **odds ratios**, autrement dit un rapport d'**odds** ou de **cotes** entre deux popultions (entre la population avec une différence de 1 dans cette variable). Les **odds** sont définis de la manière suivantes $$\n  \\text{odds} = \\frac{P(Y=1)}{P(Y=0)} \\quad \\text{ou à l'inverse} \\quad P(Y=1) = \\frac{\\text{odds}}{1 + \\text{odds}}\n$$ On peut voir ces odds ratios comme des **facteurs multiplicatifs** sur les odds : la valeur neutre (l'absence d'effet) n'est plus 0, mais 1, et :\n\n-   Si l'odds ratio est \\> 1 : La variable augmente les chances de succès.\n-   Si l'odds ratio est \\< 1 : La variable diminue les chances de succès.\n\nPar exemple, comme l'odds ratio pour education_num vaut 2.39, cela signifie que pour chaque niveau d'éducation supplémentaire acquis, en maintenant l'âge constant, les chances d'avoir un haut salaire sont multipliées par 2.39 par rapport aux chances d'avoir un bas salaire (on passe, p.ex, de 2 chances contre une à 4.78 chances contre une).\n\nContrairement à la fonction `augment()` classique (de `broom`), pour un `glm`, il faut explicitement préciser que l'on veut récupérer des probabilités (et non des log-odds) en utilisant l'argument `type.predict=\"response\"` :\n\n\n::: {.cell}\n\n```{.r .cell-code}\nglm_augm = augment(glm_res, type.predict = \"response\")\nglm_augm\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 3,000 × 9\n   high_wage   age education_num .fitted .resid     .hat .sigma    .cooksd\n       <dbl> <int>         <dbl>   <dbl>  <dbl>    <dbl>  <dbl>      <dbl>\n 1         0    18             1  0.0292 -0.244 0.000647  1.00  0.00000650\n 2         0    24             4  0.332  -0.899 0.00187   1.000 0.000312  \n 3         1    45             3  0.290   1.57  0.000455  1.000 0.000371  \n 4         1    43             4  0.478   1.21  0.000642  1.000 0.000234  \n 5         0    50             2  0.167  -0.605 0.000761  1.00  0.0000510 \n 6         1    54             4  0.566   1.07  0.00108   1.000 0.000277  \n 7         1    44             3  0.284   1.59  0.000445  1.000 0.000375  \n 8         0    30             3  0.202  -0.671 0.000847  1.000 0.0000714 \n 9         0    41             3  0.264  -0.784 0.000452  1.000 0.0000543 \n10         1    52             2  0.176   1.86  0.000853  0.999 0.00133   \n# ℹ 2,990 more rows\n# ℹ 1 more variable: .std.resid <dbl>\n```\n\n\n:::\n:::\n\n\n`.fitted` indique alors les probabilités prédites d'avoir un haut salaire pour chaque individu du jeu de données.\n\nPour évaluer la qualité du modèle, nous devons d'abord transformer ces probabilités continues en décisions d'affectation rigides (0 ou 1, en utilisant le seuil de 0.5), et calculer la **matrice de confusion** :\n\n\n::: {.cell}\n\n```{.r .cell-code}\nglm_augm = glm_augm %>%\n  mutate(prediction = ifelse(.fitted > 0.5, 1, 0))\ntable(real=glm_augm$high_wage, prediction=glm_augm$prediction)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n    prediction\nreal    0    1\n   0 1782  265\n   1  510  443\n```\n\n\n:::\n:::\n\n\nDans un prochain cours, cette matrice va nous servir à calculer plusieurs métriques d'évaluation du modèle, comme l'**exactitude** (accuracy), la **précision** (precision) ou le **rappel** (recall).\n\n## La sélection de modèles {#sec-select}\n\nDans cette dernière partie, nous abordons un problème central en statistiques appliquées : comment choisir le \"meilleur\" modèle parmi toutes les combinaisons possibles de variables ?\n\nOn pourrait être tenté d'inclure systématiquement toutes les variables disponibles dans notre jeu de données. Cependant, c'est une très mauvaise pratique à cause du **surapprentissage** (*overfitting*). Un modèle trop complexe, avec trop de variables, va apprendre \"par coeur\" l'échantillon (y compris le bruit aléatoire) et sera incapable de faire de bonnes prédictions sur de nouvelles données. Le principe de base est celui de la **parcimonie** (le rasoir d'Ockham) : on cherche le modèle qui explique le maximum de variance avec le minimum de complexité.\n\n### Les critères d'information : AIC et BIC\n\nPour comparer des modèles, nous ne pouvons pas utiliser le simple $R^2$. En effet, mathématiquement, le $R^2$ augmente toujours lorsqu'on ajoute une variable, même si celle-ci est totalement absurde.\n\nÀ la place, nous utilisons les **critères d'information**, qui mesurent l'erreur du modèle tout en appliquant une pénalité pour chaque variable ajoutée. Ces métriques fonctionnent dans le même sens : on cherche le modèle qui les minimise.\n\n-   **L'AIC (Akaike Information Criterion)** : $$AIC = 2k - 2\\ln(\\hat{L})$$ (où $k$ est le nombre de paramètres et $\\hat{L}$ la vraisemblance du modèle). L'AIC est très utilisé lorsque l'objectif du modèle est de faire de la **prédiction**.\n\n-   **Le BIC (Bayesian Information Criterion)** : $$BIC = \\ln(n)k - 2\\ln(\\hat{L})$$ (où $n$ est la taille de l'échantillon). La pénalité du BIC dépend de la taille de l'échantillon. En pratique, dès que l'on a plus de 8 observations, le BIC pénalise la complexité beaucoup plus sévèrement que l'AIC. Il favorise des modèles plus simples et est idéal lorsque l'objectif est d'**expliquer** le phénomène et d'identifier les vrais facteurs clés.\n\nComparons manuellement deux modèles avec la fonction `glance()` (du package `broom`) qui nous donne ces différentes métriques :\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Modèle simple\nlm_simple = lm(wage ~ age, wage_df)\n\n# Modèle plus complexe\nlm_complex = lm(wage ~ age + education_num + jobclass, wage_df)\n\n# Comparaison des métriques\nglance(lm_simple)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 1 × 12\n  r.squared adj.r.squared sigma statistic  p.value    df  logLik    AIC    BIC\n      <dbl>         <dbl> <dbl>     <dbl>    <dbl> <dbl>   <dbl>  <dbl>  <dbl>\n1    0.0383        0.0380  40.9      119. 2.90e-27     1 -15391. 30789. 30807.\n# ℹ 3 more variables: deviance <dbl>, df.residual <int>, nobs <int>\n```\n\n\n:::\n\n```{.r .cell-code}\nglance(lm_complex)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 1 × 12\n  r.squared adj.r.squared sigma statistic   p.value    df  logLik    AIC    BIC\n      <dbl>         <dbl> <dbl>     <dbl>     <dbl> <dbl>   <dbl>  <dbl>  <dbl>\n1     0.256         0.255  36.0      343. 1.96e-191     3 -15007. 30024. 30054.\n# ℹ 3 more variables: deviance <dbl>, df.residual <int>, nobs <int>\n```\n\n\n:::\n:::\n\n\nLe modèle complexe possède un AIC et un BIC légérement inférieurs à ceux du modèle simple. L'ajout des variables `education_num` et `jobclass` est donc statistiquement justifié : le gain d'information dépasse la pénalité de complexité.\n\nRegradons maintenant deux méthodes automatiques de recherche de modèles, qui marchent aussi bien avec `lm()` qu'avec `glm()`.\n\n### L'approche gloutonne\n\nLorsque nous avons de nombreuses variables potentielles, comparer les modèles à la main devient impossible. R propose une fonction native, `step()`, qui automatise ce processus.\n\nC'est un algorithme dit **glouton** ou **heuristique**, qui part d'un modèle initial, et \"avance\" (comprendre: retire ou ajoute une variable) dans la direction qui améliore au mieux la métrique choisie. Par exemple, si l'on choisit la direction \"backward\", l'algorithme part d'un modèle complet (toutes les variables), évalue quelle variable retirer pour améliorer au mieux le BIC, la retire, et recommence jusqu'à ce que plus aucun retrait n'améliore le score. Regardons justement comment cet exemple fonctionne ici.\n\nOn commence par sélectionner toutes le variables qui nous semblent pertinentes pour notre modèle :\n\n\n::: {.cell}\n\n```{.r .cell-code}\nwage_reduced_df = wage_df %>%\n  select(age, maritl, race, education_num, jobclass, wage, health_cat)\n```\n:::\n\n\nOn va maintenant définir le modèle complet, c'est-à-dire avec toutes les variables restantes :\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlm_full = lm(wage ~ ., wage_reduced_df)\n```\n:::\n\n\nAvec, `step()`, on lance la sélection automatique en choisissant la `direction=\"backward\"` (on peut aussi faire \"forward\" ou \"both\") et en précisant que l'on veut utiliser le BIC pour évaluer les modèles (pour cela on doit définir l'argument `k` comme $\\ln(n)$, avec $n$ le nombre d'observations) :\n\n\n::: {.cell}\n\n```{.r .cell-code}\nn = nrow(wage_reduced_df)\nlm_optimal_wstep = step(lm_full, direction=\"backward\", k=log(n))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nStart:  AIC=21427.77\nwage ~ age + maritl + race + education_num + jobclass + health_cat\n\n                Df Sum of Sq     RSS   AIC\n- race           3      9757 3684278 21412\n<none>                       3674521 21428\n- jobclass       1     17541 3692062 21434\n- health_cat     1     33275 3707796 21447\n- age            1     44403 3718924 21456\n- maritl         4    146563 3821084 21513\n- education_num  1    779121 4453642 21997\n\nStep:  AIC=21411.71\nwage ~ age + maritl + education_num + jobclass + health_cat\n\n                Df Sum of Sq     RSS   AIC\n<none>                       3684278 21412\n- jobclass       1     15169 3699447 21416\n- health_cat     1     34151 3718429 21431\n- age            1     43058 3727336 21439\n- maritl         4    155662 3839940 21504\n- education_num  1    812522 4496800 22002\n```\n\n\n:::\n:::\n\n\nOn peut ensuite examiner le meilleur modèle retenu :\n\n\n::: {.cell}\n\n```{.r .cell-code}\nsummary(lm_optimal_wstep)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nCall:\nlm(formula = wage ~ age + maritl + education_num + jobclass + \n    health_cat, data = wage_reduced_df)\n\nResiduals:\n     Min       1Q   Median       3Q      Max \n-109.234  -19.580   -2.925   14.571  214.541 \n\nCoefficients:\n                         Estimate Std. Error t value Pr(>|t|)    \n(Intercept)               31.1803     3.0402  10.256  < 2e-16 ***\nage                        0.3748     0.0634   5.912 3.75e-09 ***\nmaritl2. Married          18.2215     1.7610  10.347  < 2e-16 ***\nmaritl3. Widowed           1.4883     8.2501   0.180 0.856851    \nmaritl4. Divorced          4.9779     2.9692   1.677 0.093741 .  \nmaritl5. Separated        12.1753     4.9928   2.439 0.014803 *  \neducation_num             14.5034     0.5647  25.683  < 2e-16 ***\njobclass2. Information     4.7411     1.3510   3.509 0.000456 ***\nhealth_cat2. >=Very Good   7.7031     1.4629   5.265 1.50e-07 ***\n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\nResidual standard error: 35.1 on 2991 degrees of freedom\nMultiple R-squared:  0.2945,\tAdjusted R-squared:  0.2926 \nF-statistic: 156.1 on 8 and 2991 DF,  p-value: < 2.2e-16\n```\n\n\n:::\n:::\n\n\nLa limite de cet algorithme est qu'il n'explore pas toutes les possibilités. Il risque donc de se retrouver bloqué dans un optimum local et de rater le meilleur modèle absolu.\n\n### L'approche exhaustive\n\nPour obtenir le meilleur modèle possible (selon un certain critère), on peut utiliser une approche **exhaustive** qui va calculer et comparer absolument toutes les combinaisons possibles des variables. Prenons ici un nouvel objectif de prédiction : prédire si les personnes ont une assurance maladie (`health_ins`), en fonction de plusieurs variables sélectionnées.\n\nOn commence par sélectionner nos variables :\n\n\n::: {.cell}\n\n```{.r .cell-code}\nwage_reduced2_df = wage_df %>%\n  select(age, maritl, race, education_num, jobclass, health_ins, wage, health_cat)\n```\n:::\n\n\nOn fait notre `glm` complet :\n\n\n::: {.cell}\n\n```{.r .cell-code}\nglm_full = glm(health_ins ~ ., wage_reduced2_df, family=\"binomial\")\n```\n:::\n\n\nPuis on lance la sélection exhaustive avec la fonction `dredge()` du package `MuMIn`, qui va calculer tous les modèles possibles à partir du modèle complet et les classer selon la métrique choisie (ici le BIC) :\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Changement de l'option pour la gestion des NA, requis par MuMIn\noptions(na.action = \"na.fail\")\n# On lance la sélection exhaustive sur notre modèle complet précédent\nall_model_eval = dredge(glm_full, rank=\"BIC\")\n```\n\n::: {.cell-output .cell-output-stderr}\n\n```\nFixed term is \"(Intercept)\"\n```\n\n\n:::\n:::\n\n\nOn peut ensuite examiner tous les différents modèles, dans l'ordre croissant. Ici, on va afficher uniquement les 10 permiers :\n\n\n::: {.cell}\n\n```{.r .cell-code}\nhead(all_model_eval, 10)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nGlobal model call: glm(formula = health_ins ~ ., family = \"binomial\", data = wage_reduced2_df)\n---\nModel selection table \n   (Int)      age  edc_num hlt_cat jbc      wag df    logLik    BIC delta\n74 2.333 -0.01279                    + -0.02347  4 -1640.889 3313.8  0.00\n76 2.434 -0.01324 -0.08353           + -0.02214  5 -1638.849 3317.7  3.92\n73 1.910                             + -0.02450  3 -1647.008 3318.0  4.23\n78 2.455 -0.01405                +   + -0.02304  5 -1639.283 3318.6  4.79\n75 1.987          -0.07437           + -0.02334  4 -1645.371 3322.8  8.96\n80 2.537 -0.01434 -0.07716       +   + -0.02185  6 -1637.560 3323.2  9.35\n77 1.959                         +   + -0.02430  4 -1646.397 3324.8 11.01\n68 2.443 -0.01417 -0.11950             -0.02235  4 -1646.410 3324.8 11.04\n66 2.292 -0.01361                      -0.02443  3 -1650.843 3325.7 11.90\n70 2.428 -0.01498                +     -0.02393  4 -1648.864 3329.8 15.95\n   weight\n74  0.723\n76  0.102\n73  0.087\n78  0.066\n75  0.008\n80  0.007\n77  0.003\n68  0.003\n66  0.002\n70  0.000\nModels ranked by BIC(x) \n```\n\n\n:::\n:::\n\n\nSi le coefficient de régression apparaît ou une croix est présente, c'est que la variable a été retenue dans le modèle. On voit que le meilleur modèle selon le BIC est celui qui contient les variables `age`, `jobclass` et `wage`.\n\nOn peut ensuite obtenir ce modèle avec la fonction `get.models()`, cela nous permet d'examiner les valeurs de ses coefficients, de faire des prédictions, ou autre :\n\n\n::: {.cell}\n\n```{.r .cell-code}\nglm_best = get.models(all_model_eval, 1)[[1]]\ntidy(glm_best, exponentiate=T)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 4 × 5\n  term                   estimate std.error statistic  p.value\n  <chr>                     <dbl>     <dbl>     <dbl>    <dbl>\n1 (Intercept)              10.3     0.201       11.6  4.66e-31\n2 age                       0.987   0.00367     -3.48 4.99e- 4\n3 jobclass2. Information    0.680   0.0866      -4.45 8.55e- 6\n4 wage                      0.977   0.00158    -14.9  4.14e-50\n```\n\n\n:::\n:::\n\n\nAttention cependant, `dredge()` est soumis au problème d'**explosion combinatoire**. Au delà d'un certain nombre de variables, le nombre de modèles à tester devient trop grand pour un ordinateur standard. Dans ces situations, pour trouver un modèle adéquat, il faudra se tourner vers la sélection gloutonne ou vers des méthodes de régression pénalisée couplées avec des techniques de Machine Learning.\n",
    "supporting": [
      "Regression_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}