{
  "hash": "5ad847a906e6e449c67bdb18e3a04093",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"VIII. Les méthodes factorielles\"\nauthor: \"Guillaume Guex\"\nnumber-sections: true\nlang: fr\n---\n\n## Introduction\n\nAprès avoir étudié des méthodes prédictives telles que la régression linéaire et logistique (expliquer $Y$ en fonction de $X$), nous passons à des méthodes exploratoires : **les méthodes factorielles**. Nous allons en voir trois ici :\n\n- L'Analyse en Composantes Principales (ACP)\n- Le Positionnement Multidimensionnel (MDS)\n- L'Analyse Factorielle des Correspondances (AFC)\n\nIl n'y a donc plus de variable cible à prédire : l'objectif est de découvrir la structure cachée au sein d'un vaste ensemble de variables (ou même, dans le cas du MDS, de données non tabulaires).\n\n### Le tronc commun entre ces méthodes\n\nBien que ces trois méthodes s'appliquent à des types de données différents, les mathématiques sous-jacentes sont identiques. En effet, ces méthodes reposent sur la **réduction de dimension par décomposition spectrale** (calcul des valeurs propres et vecteurs propres d'une matrice, ou décomposition en valeurs singulières - SVD). Via ce mécanisme, elles essaient toutes de trouver la **meilleure représentation** en basse dimensionnalité de données en haute dimensionnalité.\n\nMais que signifie exactement cette idée de *meilleure représentation* ? Toutes ces méthodes recherchent en premier lieu un axe (une direction de l'espace) qui capture le maximum d'**inertie** (l'étalement des points) de la configuration. Ensuite, elles trouvent un deuxième axe, strictement orthogonal au premier, capturant le maximum d'inertie restante, et ainsi de suite. Au final, on obtient plusieurs axes de l'espace (les facteurs), tous orthogonaux entre eux, qui **expriment l'information des données de manière décroissante et maximalement compressée** sur les premiers éléments. Il suffit ensuite de ne garder que les premiers axes pour effectuer une compression avec un minimum de perte d'information.\n\n### Les différences entre les méthodes\n\nSi la mécanique interne est la même, ce qui différencie ces méthodes est **la nature des données d'entrée** et la **variété des sorties**.\n\n#### ACP\n\nL'ACP s'applique à des individus possédant plusieurs variables numériques. Elle permet non seulement d'afficher les individus dans un espace compressé (la carte factorielle), mais également d'étudier les corrélations entre les axes factoriels et les variables originales (le cercle des corrélations).\n\n#### MDS\n\nLe MDS s'applique à des données non tabulaires, c'est-à-dire à des matrices de distances ou de dissimilarités entre les individus. Il permet de reconstruire une carte spatiale (des coordonnées) à partir de simples distances, et peut être utilisé pour n'importe quelle métrique de distance. Des objets mathématiques particuliers, comme des graphes, des séries temporelles ou des séquences ADN, peuvent ainsi être représentés dans l'espace à travers une matrice de distances.\n\n#### AFC\n\nL'AFC s'applique à des tableaux de contingence, c'est-à-dire à un tableau croisé entre des modalités de deux variables catégorielles. Elle utilise la distance du $\\chi^2$ pour étudier l'attraction ou la répulsion entre les différentes modalités. L'AFC est utilisée pour analyser les relations entre les profils de ces variables qualitatives, en particulier en les visualisant via une représentation superposée appelée le *biplot*.\n\n### Les packages de l'écosystème factoriel\n\nBien que R possède des fonctions natives pour faire des analyses factorielles (comme `prcomp()` ou `cmdscale()`), elles sont quelque peu limitées. L'analyse factorielle des données étant une spécialité historique de l'école statistique française, nous allons utiliser ici la suite de packages `FactoMineR` (<http://factominer.free.fr/index_fr.html>), développée par les chercheurs d'Agrocampus Ouest et qui est aujourd'hui le standard international en R :\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(tidyverse)\nlibrary(readxl)   \nlibrary(FactoMineR) # Le moteur de calcul principal\nlibrary(factoextra) # Le moteur graphique pour l'extraction et la visualisation\nlibrary(psych)      # Pour faire un test de sphéricité de Bartlett\nlibrary(ggrepel)    # Permet d'améliorer la lisibilité des labels\n```\n:::\n\n\n## L'Analyse en Composantes Principales (ACP)\n\nAfin d'illustrer l’**ACP**, nous allons travailler sur les données `realestate_data.xlsx` (https://archive.ics.uci.edu/dataset/477/real+estate+valuation+data+set), qui contiennent des informations sur les prix de l’immobilier à Taïwan. Ce jeu de données est généralement utilisé pour prédire le prix de l’immobilier en fonction de différentes variables explicatives, mais nous allons faire plutôt une analyse exploratoire ici.\n\n### Chargement et pré-traitement des données\n\nOn commence par charger les données et jeter un coup d'oeil à leur structure :\n\n\n::: {.cell}\n\n```{.r .cell-code}\nreal_estate = read_excel(\"data/realestate_data.xlsx\")\nreal_estate\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 414 × 8\n      No transaction_date house_age distance_to_station n_stores latitude\n   <dbl>            <dbl>     <dbl>               <dbl>    <dbl>    <dbl>\n 1     1            2013.      32                  84.9       10     25.0\n 2     2            2013.      19.5               307.         9     25.0\n 3     3            2014.      13.3               562.         5     25.0\n 4     4            2014.      13.3               562.         5     25.0\n 5     5            2013.       5                 391.         5     25.0\n 6     6            2013.       7.1              2175.         3     25.0\n 7     7            2013.      34.5               623.         7     25.0\n 8     8            2013.      20.3               288.         6     25.0\n 9     9            2014.      31.7              5512.         1     25.0\n10    10            2013.      17.9              1783.         3     25.0\n# ℹ 404 more rows\n# ℹ 2 more variables: longitude <dbl>, house_price_unit <dbl>\n```\n\n\n:::\n:::\n\n\nIl y a 414 observations. La variable “transaction_date” contient une date, qui n’a pas été lue correctement. On ne va garder que l’année qui se situe avant le point :\n\n\n::: {.cell}\n\n```{.r .cell-code}\nreal_estate = real_estate %>%\n  mutate(transaction_date = as.numeric(substr(transaction_date, 1, 4)))\n```\n:::\n\n\nNous laissons ici la variable `No`, contenant le numéro de la maison. Nous le verrons plus loin, on pourra l'exclure de l'analyse et s'en servir lors de l'affichage.\n\n### Effectuer l'ACP\n\nOn effectue une ACP sur les données en utilisant la fonction `PCA` du package `FactoMineR` (mettre l'option `graph=FALSE` permet de ne pas afficher les graphiques par défaut) :\n\n\n::: {.cell}\n\n```{.r .cell-code}\npca_res = PCA(real_estate, quanti.sup=1, graph=FALSE)\n```\n:::\n\n\nL'argument `quanti.sup=1` indique que la première variable (le numéro de la maison) est une variable quantitative **supplémentaire**, qui ne sera pas utilisée pour construire les axes factoriels, mais qui pourra être projetée a posteriori sur la carte factorielle. On peut également déclarer des variables catégorielles supplémentaires avec `quali.sup`.\n\nLa variable dans laquelle nous avons sauvegardé les résultats de l'ACP, `pca_res`, est un objet de classe `PCA` qui contient toutes les informations sur les résultats de l'ACP :\n\n\n::: {.cell}\n\n```{.r .cell-code}\npca_res\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n**Results for the Principal Component Analysis (PCA)**\nThe analysis was performed on 414 individuals, described by 8 variables\n*The results are available in the following objects:\n\n   name               \n1  \"$eig\"             \n2  \"$var\"             \n3  \"$var$coord\"       \n4  \"$var$cor\"         \n5  \"$var$cos2\"        \n6  \"$var$contrib\"     \n7  \"$ind\"             \n8  \"$ind$coord\"       \n9  \"$ind$cos2\"        \n10 \"$ind$contrib\"     \n11 \"$quanti.sup\"      \n12 \"$quanti.sup$coord\"\n13 \"$quanti.sup$cor\"  \n14 \"$call\"            \n15 \"$call$centre\"     \n16 \"$call$ecart.type\" \n17 \"$call$row.w\"      \n18 \"$call$col.w\"      \n   description                                              \n1  \"eigenvalues\"                                            \n2  \"results for the variables\"                              \n3  \"coord. for the variables\"                               \n4  \"correlations variables - dimensions\"                    \n5  \"cos2 for the variables\"                                 \n6  \"contributions of the variables\"                         \n7  \"results for the individuals\"                            \n8  \"coord. for the individuals\"                             \n9  \"cos2 for the individuals\"                               \n10 \"contributions of the individuals\"                       \n11 \"results for the supplementary quantitative variables\"   \n12 \"coord. for the supplementary quantitative variables\"    \n13 \"correlations suppl. quantitative variables - dimensions\"\n14 \"summary statistics\"                                     \n15 \"mean of the variables\"                                  \n16 \"standard error of the variables\"                        \n17 \"weights for the individuals\"                            \n18 \"weights for the variables\"                              \n```\n\n\n:::\n:::\n\n\nOn peut y accéder via l'opérateur `$`, mais il existe des manières moins \"austères\" pour afficher les résultats importants. C'est ce que nous allons voir ci-dessous.\n\n### L'inertie expliquée sur chaque axe\n\nCommençons par observer les **valeurs propres** qui expriment la variance expliquée sur chaque facteur (avec la fonction `get_eigenvalue()` de `factoextra`) :\n\n\n::: {.cell}\n\n```{.r .cell-code}\neig_vals = get_eigenvalue(pca_res)\neig_vals\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n      eigenvalue variance.percent cumulative.variance.percent\nDim.1  3.2715008        46.735726                    46.73573\nDim.2  1.0771175        15.387393                    62.12312\nDim.3  0.9983295        14.261850                    76.38497\nDim.4  0.6361083         9.087262                    85.47223\nDim.5  0.5533467         7.904953                    93.37718\nDim.6  0.3185875         4.551251                    97.92843\nDim.7  0.1450097         2.071567                   100.00000\n```\n\n\n:::\n:::\n\n\nOn peut visualiser cette variance expliquée par chaque facteur avec le **screegraph**, via la fonction `fviz_screeplot()` de `factoextra`) :\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# addlabels=T ajoute les valeurs d'inertie sur le graphique et ylim=c(0, 50) fixe les limites de l'axe des ordonnées\nfviz_screeplot(pca_res, addlabels=T, ylim=c(0, 50))\n```\n\n::: {.cell-output-display}\n![](Methodes_factorielles_files/figure-html/unnamed-chunk-7-1.png){width=672}\n:::\n:::\n\n\nGrâce à ces éléments, on pourrait décider du nombre de facteurs selon différents critères :\n\n- Selon le *critère de Jolliffe* (garder 90% de la variance), on garderait 5 facteurs.\n- Selon le *critère de Kaiser* (valeurs propres \\> moyenne = 1), on garderait 2 facteurs.\n- Selon le *critère de Cattell ou du coude* (chercher un coude dans le screegraph), on garderait 1 facteur.\n\nEffectuons maintenant un **test de Bartlett** pour vérifier que l'ACP est pertinente :\n\n\n::: {.cell}\n\n```{.r .cell-code}\ncortest.bartlett(real_estate[, -1])\n```\n\n::: {.cell-output .cell-output-stderr}\n\n```\nR was not square, finding R from data\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stdout}\n\n```\n$chisq\n[1] 1172.576\n\n$p.value\n[1] 4.247946e-235\n\n$df\n[1] 21\n```\n\n\n:::\n:::\n\n\nL'hypothèse $H_0$ : \"toutes les valeurs propres sont égales\" est largement rejetée, notre ACP est donc pertinente.\n\n### Le cercle des corrélations\n\nOn peut visualiser le **cercle des corrélations** pour observer les contributions des variables aux différents facteurs. Ce cercle des corrélations peut être affiché via la fonction `fviz_pca_var()` :\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# On définit des couleurs pour la somme des contributions, on rend la variable supplémentaire invisible et on active le \"repel\", qui empêche les superpositions\nfviz_pca_var(pca_res, col.var=\"contrib\",\n             gradient.cols=c(\"#00AFBB\", \"#E7B800\", \"#FC4E07\"),\n             invisible=\"quanti.sup\",\n             repel=TRUE)\n```\n\n::: {.cell-output-display}\n![](Methodes_factorielles_files/figure-html/unnamed-chunk-9-1.png){width=672}\n:::\n:::\n\n\nLes *communalités* (vues plus loin) des variables sur les deux premiers facteurs ont été utilisées pour la coloration. Ce graphique exprime **46.7% + 15.4% = 62.1% de la variance totale**.\n\nCe graphique montre que le **premier facteur** comprend les variables :\n\n- (positivement) le prix au m2\n- (positivement) la latitude\n- (positivement) la longitude\n- (positivement) le nombre de commerces\n- (négativement) la distance aux transports publics\n\nOn pourrait nommer cet axe **\"Attractivité du bâtiment\"**.\n\nLe **deuxième facteur** lie :\n\n- (positivement) âge de la maison\n- (positivement) date de vente\n\nEn réalité cet axe est presque entièrement lié à l'âge de la maison, qui semble orthogonal à toutes les autres variables.\n\nCe graphique est basé sur les **saturations** (correlations entre variables et facteurs)\n\n\n::: {.cell}\n\n```{.r .cell-code}\nsaturations = pca_res$var$coord[, 1:2]\nsaturations\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n                          Dim.1        Dim.2\ntransaction_date     0.02694038  0.408239197\nhouse_age           -0.06978933  0.918311455\ndistance_to_station -0.91903422 -0.009603627\nn_stores             0.75106955  0.122938634\nlatitude             0.72901893  0.151597096\nlongitude            0.79972168 -0.023712815\nhouse_price_unit     0.82834278 -0.168559219\n```\n\n\n:::\n:::\n\n\nLes **saturations carrées** ou **cos2** expriment le pourcentage de variance d'une variable expliquée par un facteur :\n\n\n::: {.cell}\n\n```{.r .cell-code}\npca_res$var$cos2[, 1:2]\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n                           Dim.1        Dim.2\ntransaction_date    0.0007257842 1.666592e-01\nhouse_age           0.0048705500 8.432959e-01\ndistance_to_station 0.8446238942 9.222966e-05\nn_stores            0.5641054635 1.511391e-02\nlatitude            0.5314686048 2.298168e-02\nlongitude           0.6395547589 5.622976e-04\nhouse_price_unit    0.6861517567 2.841221e-02\n```\n\n\n:::\n:::\n\n\nEt les **communalités**, qui sont la somme de ces dernières sur les deux premiers facteurs, expriment alors le pourcentage de variance des variables sur ces deux axes :\n\n\n::: {.cell}\n\n```{.r .cell-code}\nrowSums(pca_res$var$cos2[, 1:2])\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n   transaction_date           house_age distance_to_station            n_stores \n          0.1673850           0.8481665           0.8447161           0.5792194 \n           latitude           longitude    house_price_unit \n          0.5544503           0.6401171           0.7145640 \n```\n\n\n:::\n:::\n\n\nOn voit que les variables `house_age` (84.81%), `distance_to_station` (84.47%) et `house_price_unit` (71.45%) sont les mieux exprimées sur ces axes.\n\n### Coordonnées factorielles\n\nOn peut observer les **coordonnées factorielles** des observations sur les deux premiers facteurs avec `fviz_pca_ind()` :\n\n\n::: {.cell}\n\n```{.r .cell-code}\nfviz_pca_ind(pca_res)\n```\n\n::: {.cell-output-display}\n![](Methodes_factorielles_files/figure-html/unnamed-chunk-13-1.png){width=672}\n:::\n:::\n\n\nLes individus étant anonymes dans ce jeu de données, ce graphique n'est pas très informatif. On pourrait les colorer selon une variable catégorielle (en utilisant l'argument `habillage=\"<nom_de_variable>\"`, même si celle-ci est une variable supplémentaire), mais il n'y en a pas dans ce jeu de données.\n\nNous allons donc les colorer ici selon un gradient d'une des variables numériques. Commençons par `house_age`, qui est la variable la mieux représentée sur ces deux axes :\n\n\n::: {.cell}\n\n```{.r .cell-code}\nfviz_pca_ind(pca_res,\n             geom=\"point\",\n             col.ind = real_estate$house_age,\n             gradient.cols = c(\"#00AFBB\", \"#E7B800\", \"#FC4E07\"))\n```\n\n::: {.cell-output-display}\n![](Methodes_factorielles_files/figure-html/unnamed-chunk-14-1.png){width=672}\n:::\n:::\n\n\nComme attendu, les maisons plus récentes (en bleu) se situent en bas du graphique (âge faible sur le deuxième facteur).\n\nFaisons de même avec `distance_to_station`.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nfviz_pca_ind(pca_res,\n             geom=\"point\",\n             col.ind = real_estate$distance_to_station,\n             gradient.cols = c(\"#00AFBB\", \"#E7B800\", \"#FC4E07\"))\n```\n\n::: {.cell-output-display}\n![](Methodes_factorielles_files/figure-html/unnamed-chunk-15-1.png){width=672}\n:::\n:::\n\n\nOn observe que les maisons plus proches des transports publics (en bleu) se situent à droite du graphique (corrélation négative avec le premier facteur).\n\n## Le Positionnement Multidimensionnel (MDS)\n\nTout l'intérêt du **MDS** est de pouvoir **construire des points dans l'espace à partir d'une matrice de dissimilarité euclidienne carrée**. Il n'est donc pas nécessaire d'avoir des données tabulaires, mais uniquement des objets dont il est possible de construire des indices de similarités ou dissimilarités pour pouvoir ensuite les représenter.\n\n### Chargement des données\n\nPour illustrer la puissance du MDS, nous allons utiliser le jeu de données `eurodist` intégré à R. Il contient uniquement les distances routières (en km) entre 21 villes européennes dans les années 1960.\n\nVoici la matrice de distances entre les 5 premières villes (les autres sont similaires) :\n\n\n::: {.cell}\n\n```{.r .cell-code}\ndist_mat = as.matrix(eurodist)\ndist_mat[1:5, 1:5]\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n          Athens Barcelona Brussels Calais Cherbourg\nAthens         0      3313     2963   3175      3339\nBarcelona   3313         0     1318   1326      1294\nBrussels    2963      1318        0    204       583\nCalais      3175      1326      204      0       460\nCherbourg   3339      1294      583    460         0\n```\n\n\n:::\n:::\n\n\n### Effectuer le MDS (pondéré)\n\nIl existe bien une fonction pour faire du MDS dans R, qui s'appelle `cmdscale()`. Elle prend en entrée une matrice de distances et retourne les coordonnées des points dans l'espace. Cependant, on va construire ici une fonction spécialisée qui permet de faire un **MDS pondéré** :\n\n\n::: {.cell}\n\n```{.r .cell-code}\nweighted_mds = function(dist, weights=NULL, k_max=NULL) {\n  \n  # La taille de la matrice \n  n = nrow(dist)\n  \n  # Si il n'y a pas de poids ou si incompatibles, on pose de poids uniformes\n  if (is.null(weights) || length(weights) != n) {\n    weights = rep(1, n)\n  }\n  \n  # On normalise les poids \n  weights = weights / sum(weights)\n  \n  # Si k_max n'est pas spécifié ou est supérieur à n-1, on le fixe à n-1\n  if (is.null(k_max) || k_max > (n-1)) {\n    k_max = n-1\n  }\n  \n  # Calcul des produits scalaires\n  H = diag(n) - matrix(1/n, n, n)\n  B = -0.5 * H %*% (dist^2) %*% H\n  \n  # Décomposition spectrale\n  eigen_B = eigen(B)\n  eigen_val = eigen_B$values\n  eigen_vec = eigen_B$vectors\n  \n  # Suppression des valeurs propres négatives (si non-euclidien)\n  eigen_val[eigen_val < 0] = 0\n  \n  # Reconstruction des coordonnées (1 à k_max seulement)\n  coord = eigen_vec[, 1:k_max] %*% diag(sqrt(eigen_val[1:k_max]))\n  \n  # On retourne les valeurs propres et les coordonnées\n  return(list(eigenvalues=eigen_val, coordinates=coord))\n}\n```\n:::\n\n\nOn peut maintenant appliquer cette fonction à notre matrice de distances pour effectuer notre MDS :\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmds_res = weighted_mds(dist_mat)\n```\n:::\n\n\nComme défini dans la fonction, `mds_res` contient les valeurs propres et les coordonnées des points dans l'espace. Il existe moins de sorties possibles que pour l'ACP ou l'AFC, car nous n'avons normalement pas accès aux variables originales.\n\n### L'inertie expliquée sur chaque axe\n\nLa sortie `eigenvalues` contient les valeurs propres :\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmds_res$eigenvalues\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n [1] 19538377.09 11856555.33  1528844.47  1118741.95   789347.20   581655.21\n [7]   262319.21   192597.56   145084.53   107967.31    51394.84        0.00\n[13]        0.00        0.00        0.00        0.00        0.00        0.00\n[19]        0.00        0.00        0.00\n```\n\n\n:::\n:::\n\n\nOn voit que de nombreuses valeurs ont été annulées (elles étaient négatives avant, mais notre fonction les a mises à 0), ce qui indique que notre dissimilarité d'entrée n'était **pas euclidienne carrée**.\n\nOn va tracer le **screeplot** illustrant la répartition de l'inertie sur chaque axe :\n\n\n::: {.cell}\n\n```{.r .cell-code}\neigen_df = data.frame(id = 1:length(mds_res$eigenvalues), \n                      inertia = mds_res$eigenvalues/sum(mds_res$eigenvalues) )\n\nggplot(eigen_df, aes(x=id, y=inertia)) +\n  geom_point() +\n  geom_line() +\n  xlab(\"Dimension\") +\n  ylab(\"Proportion d'inertie\")\n```\n\n::: {.cell-output-display}\n![](Methodes_factorielles_files/figure-html/unnamed-chunk-20-1.png){width=672}\n:::\n:::\n\n\nEn utilisant le critère du coude, on voit que l'on ne garderait que les deux premières dimensions, ce qui n'est pas surprenant pour des données issues d'une carte bidimensionnelle.\n\n### Les coordonnées factorielles\n\nOn va maintenant utiliser les coordonnées factorielles pour reconstruire une carte des villes à partir de leurs distances routières. Nous allons utiliser les deux premières dimensions pour cela, ce qui correspond à une projection en 2D de la configuration originale :\n\n\n::: {.cell}\n\n```{.r .cell-code}\nind_df = data.frame(ville = rownames(dist_mat), \n                    x = mds_res$coordinates[, 1], \n                    y = mds_res$coordinates[, 2])\n\nggplot(ind_df, aes(x = x, y = y, label = ville)) +\n  geom_point(color = \"darkred\", size = 2) +\n  geom_text_repel(size = 3.5, color = \"darkblue\") +\n  theme_minimal() +\n  labs(title = \"Carte reconstruite par MDS (Distances routières)\",\n       x = \"Dimension 1\",\n       y = \"Dimension 2\")\n```\n\n::: {.cell-output-display}\n![](Methodes_factorielles_files/figure-html/unnamed-chunk-21-1.png){width=672}\n:::\n:::\n\n\nSur ce graphique, la forme de l'Europe apparaît mais la carte n'est pas dans le bon sens. En réalité, l'orientation des axes n'a aucune signification absolue. L'algorithme préserve strictement les distances relatives entre les points, mais comme il ne connaît pas les concepts géographiques de \"Nord\" ou \"Sud\", la projection finale est arbitraire dans son orientation (c'est invariant par rotation ou symétrie).\n\nDans ce cas précis, on peut remettre la carte dans le bon sens en inversant l'axe $y$ :\n\n\n::: {.cell}\n\n```{.r .cell-code}\nggplot(ind_df, aes(x = x, y = -y, label = ville)) +\n  geom_point(color = \"darkred\", size = 2) +\n  geom_text_repel(size = 3.5, color = \"darkblue\") +\n  theme_minimal() +\n  labs(title = \"Carte reconstruite par MDS (Distances routières)\",\n       x = \"Dimension 1\",\n       y = \"Dimension 2\")\n```\n\n::: {.cell-output-display}\n![](Methodes_factorielles_files/figure-html/unnamed-chunk-22-1.png){width=672}\n:::\n:::\n\n\n## L'Analyse Factorielle des Correspondances (AFC)\n\nL'**AFC** est une méthode d'analyse factorielle adaptée aux données qualitatives. Elle permet d'analyser les relations entre les modalités de **deux variables catégorielles** à partir d'une **table de contingence** (si vous avez des données tabulaires, utilisez la fonction `table()` pour l'obtenir). L'AFC utilise la distance du $\\chi^2$ pour mesurer les associations entre les modalités, et produit une représentation graphique appelée **biplot**, où les modalités des deux variables sont représentées dans le même espace.\n\nElle est particulièrement adaptée pour analyser des données textuelles mises sous forme de table **document-terme** (le paradigme *Bag-of-Words*), c'est-à-dire un tableau contenant sur les lignes des documents, sur les colonnes des termes, et dans les cases le nombre de fois que le terme est utilisé dans le document en question. C'est avec un exemple de telles données que nous allons effectuer l'AFC.\n\n### Le jeu de données\n\nNous allons utiliser ici le jeu de données `manifesto_dtf.csv`, qui contient les fréquences de plusieurs termes utilisés dans des manifestes politiques émis lors des élections présidentielles et législatives françaises en 2017. Cette table de contingence a été construite à partir de textes extraits du **Manifesto Project** <https://manifesto-project.wzb.eu/>.\n\nOn commence par charger la table de contingence :\n\n\n::: {.cell}\n\n```{.r .cell-code}\ndtf = read_csv(\"data/manifesto_dtf.csv\") %>%\n  column_to_rownames(\"doc_id\") # on utilise la colonne \"doc_id\" comme nom des lignes\n```\n\n::: {.cell-output .cell-output-stderr}\n\n```\nRows: 9 Columns: 7567\n── Column specification ────────────────────────────────────────────────────────\nDelimiter: \",\"\nchr    (1): doc_id\ndbl (7566): emmanuel, macron, président, retrouver, esprit, conquête, bâtir,...\n\nℹ Use `spec()` to retrieve the full column specification for this data.\nℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.\n```\n\n\n:::\n\n```{.r .cell-code}\nas_tibble(dtf)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 9 × 7,566\n  emmanuel macron président retrouver esprit conquête bâtir france nouvelle\n     <dbl>  <dbl>     <dbl>     <dbl>  <dbl>    <dbl> <dbl>  <dbl>    <dbl>\n1        1      1         3         2      4        2     2     21        5\n2        0      0         0         1      0        0     0     38        2\n3        0      2         6         2      5        0     1     64       18\n4        0      0         0         2      1        0     1     36        2\n5        0      0         4         2      1        0     4     36       10\n6        0      1         1         0      0        0     0      0        1\n7        0      0         6         0      0        2     0     21        6\n8        0      0         0         0      0        0     0      7        0\n9        2      2         2         1      2        0     0     35        6\n# ℹ 7,557 more variables: contrat <dbl>, nation <dbl>, programme <dbl>,\n#   construit <dbl>, vivre <dbl>, travail <dbl>, inventer <dbl>,\n#   nouvelles <dbl>, protections <dbl>, sommes <dbl>, condamnés <dbl>,\n#   choisir <dbl>, chômage <dbl>, masse <dbl>, précarisation <dbl>,\n#   naïfs <dbl>, savons <dbl>, vie <dbl>, progrès <dbl>, personnel <dbl>,\n#   collectif <dbl>, dépend <dbl>, effort <dbl>, appelle <dbl>, lorsqu <dbl>,\n#   pratiqué <dbl>, bonnes <dbl>, conditions <dbl>, correctement <dbl>, …\n```\n\n\n:::\n:::\n\n\n### Effectuer l'AFC\n\nL'analyse factorielle des correspondances s'effectue avec la fonction **`CA()`** (\"correspondence analysis\") de `FactoMineR` (toujours, sans graphique automatique avec `graph=F`) :\n\n\n::: {.cell}\n\n```{.r .cell-code}\nca_res = CA(dtf, graph=F)\n```\n:::\n\n\nDe manière similaire au retour de `PCA()`, on peut accéder à de nombreuses valeurs via ce retour :\n\n\n::: {.cell}\n\n```{.r .cell-code}\nca_res\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n**Results of the Correspondence Analysis (CA)**\nThe row variable has  9  categories; the column variable has 7566 categories\nThe chi square of independence between the two variables is equal to 70978.31 (p-value =  8.514571e-179 ).\n*The results are available in the following objects:\n\n   name              description                   \n1  \"$eig\"            \"eigenvalues\"                 \n2  \"$col\"            \"results for the columns\"     \n3  \"$col$coord\"      \"coord. for the columns\"      \n4  \"$col$cos2\"       \"cos2 for the columns\"        \n5  \"$col$contrib\"    \"contributions of the columns\"\n6  \"$row\"            \"results for the rows\"        \n7  \"$row$coord\"      \"coord. for the rows\"         \n8  \"$row$cos2\"       \"cos2 for the rows\"           \n9  \"$row$contrib\"    \"contributions of the rows\"   \n10 \"$call\"           \"summary called parameters\"   \n11 \"$call$marge.col\" \"weights of the columns\"      \n12 \"$call$marge.row\" \"weights of the rows\"         \n```\n\n\n:::\n:::\n\n\nMais nous allons utiliser encore une fois les fonctions de `factoextra` pour extraire et visualiser les résultats importants de manière plus esthétique.\n\n### L'inertie expliquée sur chaque axe\n\nCommençons par observer la **valeurs propres** qui expriment la variance expliquée sur chaque facteur (avec la fonction `get_eigenvalue()` de `factoextra`) :\n\n\n::: {.cell}\n\n```{.r .cell-code}\nget_eigenvalue(ca_res)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n      eigenvalue variance.percent cumulative.variance.percent\nDim.1  0.3741426        16.698711                    16.69871\nDim.2  0.3370321        15.042397                    31.74111\nDim.3  0.2893282        12.913280                    44.65439\nDim.4  0.2825024        12.608631                    57.26302\nDim.5  0.2681149        11.966490                    69.22951\nDim.6  0.2588573        11.553305                    80.78282\nDim.7  0.2500510        11.160263                    91.94308\nDim.8  0.1805192         8.056922                   100.00000\n```\n\n\n:::\n\n```{.r .cell-code}\nfviz_screeplot(ca_res, addlabels=T, ylim=c(0, 50))\n```\n\n::: {.cell-output-display}\n![](Methodes_factorielles_files/figure-html/unnamed-chunk-26-1.png){width=672}\n:::\n:::\n\n\nContrairement aux autres résultats, on voit qu'ici la méthode ne compresse pas si bien l'inertie sur les deux premières dimensions : il existe donc de nombreux contrastes importants si l'on affiche que les deux premières dimensions.\n\n### Le biplot\n\nLes fonctions `fviz_ca_row()` et `fviz_ca_col()` permettent d'afficher respectivement les modalités des lignes et des colonnes de la table de contingence. Cependant, lorsque l'on effectue une AFC, on peut afficher les deux résultats sur le même graphique. Cette représentation se nomme le **biplot**. On l'obtient avec la fonction `fviz_ca_biplot()` :\n\n\n::: {.cell}\n\n```{.r .cell-code}\nfviz_ca_biplot(ca_res, geom=\"text\", labelsize=2)\n```\n\n::: {.cell-output-display}\n![](Methodes_factorielles_files/figure-html/unnamed-chunk-27-1.png){width=672}\n:::\n:::\n\n\nLe problème est qu'il y a beaucoup trop de mots pour y voir quelque chose (même en diminuant la taille du texte avec `labelsize`). Une solution est d'utiliser certaines quantités de l'AFC pour sélectionner des colonnes (ou des lignes) à afficher.\n\nPar exemple, on peut utiliser les **contributions** des modalités à la construction des axes pour n'afficher que les modalités les plus contributives. Ces dernières s'affichent avec :\n\n\n::: {.cell}\n\n```{.r .cell-code}\nfviz_contrib(ca_res, choice=\"col\", axes=1:2, top=30)\n```\n\n::: {.cell-output-display}\n![](Methodes_factorielles_files/figure-html/unnamed-chunk-28-1.png){width=672}\n:::\n:::\n\n\nOu alors, les **cos2**, c'est-à-dire la qualité de représentation des modalités sur les axes, représentables avec :\n\n\n::: {.cell}\n\n```{.r .cell-code}\nfviz_cos2(ca_res, choice=\"col\", axes=1:2, top=30)\n```\n\n::: {.cell-output-display}\n![](Methodes_factorielles_files/figure-html/unnamed-chunk-29-1.png){width=672}\n:::\n:::\n\n\nHeureusement, le package `factoextra` nous facilite la tâche en n'utilisant qu'une seule option dans la fonction `fviz_ca_biplot()` pour effectuer une sélection automatique :\n\n\n::: {.cell}\n\n```{.r .cell-code}\nfviz_ca_biplot(ca_res, repel=T, select.col=list(contrib=30))\n```\n\n::: {.cell-output-display}\n![](Methodes_factorielles_files/figure-html/unnamed-chunk-30-1.png){width=672}\n:::\n:::\n\n\nVous pouvez voir que l'option `select.col`, ou `select.row`, peut prendre différentes métriques pour faire la sélection automatique.\n\nD'autres dimensions peuvent également être affichées :\n\n\n::: {.cell}\n\n```{.r .cell-code}\nfviz_ca_biplot(ca_res, axes=c(3, 4), repel=T, select.col=list(contrib=30))\n```\n\n::: {.cell-output-display}\n![](Methodes_factorielles_files/figure-html/unnamed-chunk-31-1.png){width=672}\n:::\n:::\n\n\nMais ici, le document du parti communiste français, par son particularisme, semble absorber toute l'inertie.\n\n### Lignes ou colonnes supplémentaires\n\nComme le document du parti communiste français est si particulier, on peut éventuellement refaire une AFC en le mettant comme **ligne supplémentaire**. Attention, on doit ajouter une petite quantité à la matrice pour éviter des colonnes vides :\n\n\n::: {.cell}\n\n```{.r .cell-code}\nca_noPCF_res =  CA(dtf + 1e-50, graph=F, row.sup=6)\n```\n:::\n\n\nOn peut alors refaire nos graphiques. La ligne correspondant au parti communiste sera toujours affichée, mais n'a pas été utilisée pour définir les axes :\n\n\n::: {.cell}\n\n```{.r .cell-code}\nfviz_ca_biplot(ca_noPCF_res, repel=T, select.col=list(contrib=30))\n```\n\n::: {.cell-output-display}\n![](Methodes_factorielles_files/figure-html/unnamed-chunk-33-1.png){width=672}\n:::\n:::\n\n\nEt cette fois-ci, les dimensions 3 et 4 affichent des contrastes intéressants :\n\n\n::: {.cell}\n\n```{.r .cell-code}\nfviz_ca_biplot(ca_noPCF_res, axes=c(3, 4), repel=T, select.col=list(contrib=30))\n```\n\n::: {.cell-output-display}\n![](Methodes_factorielles_files/figure-html/unnamed-chunk-34-1.png){width=672}\n:::\n:::\n\n",
    "supporting": [
      "Methodes_factorielles_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}